// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  AccountStatsData,
  AccountStatsErrors,
  AccountStatsResponses,
  AddAccountMusicData,
  AddAccountMusicErrors,
  AddAccountMusicResponses,
  AddWarmingChannelsData,
  AddWarmingChannelsErrors,
  AddWarmingChannelsResponses,
  AdoptCampaignDiscoveryData,
  AdoptCampaignDiscoveryErrors,
  AdoptCampaignDiscoveryResponses,
  ApproveNeuroshillingScenarioData,
  ApproveNeuroshillingScenarioErrors,
  ApproveNeuroshillingScenarioResponses,
  AssignCampaignAccountData,
  AssignCampaignAccountErrors,
  AssignCampaignAccountResponses,
  AssignProxyData,
  AssignProxyErrors,
  AssignProxyResponses,
  CancelAccountTwofaEmailData,
  CancelAccountTwofaEmailErrors,
  CancelAccountTwofaEmailResponses,
  CheckAccountChannelUsernameData,
  CheckAccountChannelUsernameErrors,
  CheckAccountChannelUsernameResponses,
  CheckAccountData,
  CheckAccountErrors,
  CheckAccountResponses,
  CheckCampaignChannelBansData,
  CheckCampaignChannelBansErrors,
  CheckCampaignChannelBansResponses,
  CheckProxyData,
  CheckProxyErrors,
  CheckProxyResponses,
  ClearAccountTwofaEmailData,
  ClearAccountTwofaEmailErrors,
  ClearAccountTwofaEmailResponses,
  ClearLogsData,
  ClearLogsErrors,
  ClearLogsResponses,
  ClearNeurocommentListenerData,
  ClearNeurocommentListenerErrors,
  ClearNeurocommentListenerResponses,
  ConfirmAccountTwofaEmailData,
  ConfirmAccountTwofaEmailErrors,
  ConfirmAccountTwofaEmailResponses,
  CountCampaignChallengeOutcomesData,
  CountCampaignChallengeOutcomesErrors,
  CountCampaignChallengeOutcomesResponses,
  CountLogsData,
  CountLogsErrors,
  CountLogsResponses,
  CreateAccountChannelData,
  CreateAccountChannelErrors,
  CreateAccountChannelResponses,
  CreateCampaignData,
  CreateCampaignErrors,
  CreateCampaignResponses,
  CreateNeuroshillingCampaignData,
  CreateNeuroshillingCampaignErrors,
  CreateNeuroshillingCampaignResponses,
  CreateProxyData,
  CreateProxyErrors,
  CreateProxyResponses,
  DeleteAccountChannelData,
  DeleteAccountChannelErrors,
  DeleteAccountChannelPostData,
  DeleteAccountChannelPostErrors,
  DeleteAccountChannelPostResponses,
  DeleteAccountChannelResponses,
  DeleteAccountData,
  DeleteAccountErrors,
  DeleteAccountResponses,
  DeleteCampaignData,
  DeleteCampaignErrors,
  DeleteCampaignResponses,
  DeleteNeuroshillingCampaignData,
  DeleteNeuroshillingCampaignErrors,
  DeleteNeuroshillingCampaignResponses,
  DeleteProxyData,
  DeleteProxyErrors,
  DeleteProxyResponses,
  EditAccountChannelPostData,
  EditAccountChannelPostErrors,
  EditAccountChannelPostResponses,
  ExpandDiscoveryKeywordsData,
  ExpandDiscoveryKeywordsErrors,
  ExpandDiscoveryKeywordsResponses,
  GenerateNeuroshillingScenarioData,
  GenerateNeuroshillingScenarioErrors,
  GenerateNeuroshillingScenarioResponses,
  GetAccountChannelData,
  GetAccountChannelErrors,
  GetAccountChannelResponses,
  GetAccountLimitsData,
  GetAccountLimitsErrors,
  GetAccountLimitsResponses,
  GetAccountPrivacyData,
  GetAccountPrivacyErrors,
  GetAccountPrivacyResponses,
  GetAccountProfileSnapshotData,
  GetAccountProfileSnapshotErrors,
  GetAccountProfileSnapshotResponses,
  GetAccountTwofaData,
  GetAccountTwofaErrors,
  GetAccountTwofaResponses,
  GetCampaignDiscoveryData,
  GetCampaignDiscoveryErrors,
  GetCampaignDiscoveryResponses,
  GetHealthData,
  GetHealthErrors,
  GetHealthResponses,
  GetMeData,
  GetMeErrors,
  GetMeResponses,
  GetNeurocommentBoardData,
  GetNeurocommentBoardErrors,
  GetNeurocommentBoardResponses,
  GetNeurocommentRuntimeData,
  GetNeurocommentRuntimeErrors,
  GetNeurocommentRuntimeResponses,
  GetNeurocommentSettingsData,
  GetNeurocommentSettingsErrors,
  GetNeurocommentSettingsResponses,
  GetNeuroshillingBoardData,
  GetNeuroshillingBoardErrors,
  GetNeuroshillingBoardResponses,
  GetNeuroshillingScenarioData,
  GetNeuroshillingScenarioErrors,
  GetNeuroshillingScenarioResponses,
  GetReadinessData,
  GetReadinessErrors,
  GetReadinessResponses,
  GetWarmingBoardData,
  GetWarmingBoardErrors,
  GetWarmingBoardResponses,
  GetWarmingSettingsData,
  GetWarmingSettingsErrors,
  GetWarmingSettingsResponses,
  HandoffToNeurocommentData,
  HandoffToNeurocommentErrors,
  HandoffToNeurocommentResponses,
  ImportAccountSessionData,
  ImportAccountSessionErrors,
  ImportAccountSessionResponses,
  ImportAccountTdataData,
  ImportAccountTdataErrors,
  ImportAccountTdataResponses,
  LinkCampaignChannelData,
  LinkCampaignChannelErrors,
  LinkCampaignChannelResponses,
  ListAccountChannelPostsData,
  ListAccountChannelPostsErrors,
  ListAccountChannelPostsResponses,
  ListAccountChannelsData,
  ListAccountChannelsErrors,
  ListAccountChannelsResponses,
  ListAccountsData,
  ListAccountsErrors,
  ListAccountsResponses,
  ListCampaignChallengesData,
  ListCampaignChallengesErrors,
  ListCampaignChallengesResponses,
  ListCampaignsData,
  ListCampaignsErrors,
  ListCampaignsResponses,
  ListChannelChallengesData,
  ListChannelChallengesErrors,
  ListChannelChallengesResponses,
  ListLogsData,
  ListLogsErrors,
  ListLogsResponses,
  ListNeurocommentCommentsData,
  ListNeurocommentCommentsErrors,
  ListNeurocommentCommentsResponses,
  ListNeuroshillingCampaignsData,
  ListNeuroshillingCampaignsErrors,
  ListNeuroshillingCampaignsResponses,
  ListProxiesData,
  ListProxiesErrors,
  ListProxiesResponses,
  ListWarmedAccountsData,
  ListWarmedAccountsErrors,
  ListWarmedAccountsResponses,
  ListWarmingChannelsData,
  ListWarmingChannelsErrors,
  ListWarmingChannelsResponses,
  ListWarmingDialoguesData,
  ListWarmingDialoguesErrors,
  ListWarmingDialoguesResponses,
  LoginData,
  LoginErrors,
  LoginResponses,
  LogoutAccountData,
  LogoutAccountErrors,
  LogoutAccountResponses,
  LogoutData,
  LogoutErrors,
  LogoutResponses,
  PostAccountStoryData,
  PostAccountStoryErrors,
  PostAccountStoryResponses,
  ProbeProxyData,
  ProbeProxyErrors,
  ProbeProxyResponses,
  PromoteToNeurocommentData,
  PromoteToNeurocommentErrors,
  PromoteToNeurocommentResponses,
  PublishAccountChannelPostData,
  PublishAccountChannelPostErrors,
  PublishAccountChannelPostResponses,
  RemoveAccountMusicData,
  RemoveAccountMusicErrors,
  RemoveAccountMusicResponses,
  RemoveAccountPhotoData,
  RemoveAccountPhotoErrors,
  RemoveAccountPhotoResponses,
  RemoveAccountStoryData,
  RemoveAccountStoryErrors,
  RemoveAccountStoryResponses,
  RemoveAccountTwofaData,
  RemoveAccountTwofaErrors,
  RemoveAccountTwofaResponses,
  RemoveCampaignAccountData,
  RemoveCampaignAccountErrors,
  RemoveCampaignAccountResponses,
  RemoveCampaignChannelData,
  RemoveCampaignChannelErrors,
  RemoveCampaignChannelResponses,
  RemoveWarmingChannelData,
  RemoveWarmingChannelErrors,
  RemoveWarmingChannelResponses,
  RequestLoginCodeData,
  RequestLoginCodeErrors,
  RequestLoginCodeResponses,
  ResendAccountTwofaEmailData,
  ResendAccountTwofaEmailErrors,
  ResendAccountTwofaEmailResponses,
  ResetAccountSessionData,
  ResetAccountSessionErrors,
  ResetAccountSessionResponses,
  ResyncAccountAvatarData,
  ResyncAccountAvatarErrors,
  ResyncAccountAvatarResponses,
  SetAccountChannelPhotoData,
  SetAccountChannelPhotoErrors,
  SetAccountChannelPhotoResponses,
  SetAccountPhotoData,
  SetAccountPhotoErrors,
  SetAccountPhotoMainData,
  SetAccountPhotoMainErrors,
  SetAccountPhotoMainResponses,
  SetAccountPhotoResponses,
  SetAccountPrivacyData,
  SetAccountPrivacyErrors,
  SetAccountPrivacyResponses,
  SetAccountStoryPinnedData,
  SetAccountStoryPinnedErrors,
  SetAccountStoryPinnedResponses,
  SetAccountTwofaData,
  SetAccountTwofaEmailData,
  SetAccountTwofaEmailErrors,
  SetAccountTwofaEmailResponses,
  SetAccountTwofaErrors,
  SetAccountTwofaResponses,
  SetAllAccountsPrivacyData,
  SetAllAccountsPrivacyErrors,
  SetAllAccountsPrivacyResponses,
  SetCampaignAccountChannelData,
  SetCampaignAccountChannelErrors,
  SetCampaignAccountChannelResponses,
  SetCampaignSolverData,
  SetCampaignSolverErrors,
  SetCampaignSolverResponses,
  SetCampaignStatusData,
  SetCampaignStatusErrors,
  SetCampaignStatusResponses,
  SetNeurocommentListenerData,
  SetNeurocommentListenerErrors,
  SetNeurocommentListenerResponses,
  SetNeuroshillingScenarioData,
  SetNeuroshillingScenarioErrors,
  SetNeuroshillingScenarioResponses,
  SkipNeurocommentPairData,
  SkipNeurocommentPairErrors,
  SkipNeurocommentPairResponses,
  SpamCheckAccountData,
  SpamCheckAccountErrors,
  SpamCheckAccountResponses,
  StartCampaignDiscoveryData,
  StartCampaignDiscoveryErrors,
  StartCampaignDiscoveryResponses,
  StartNeurocommentData,
  StartNeurocommentErrors,
  StartNeurocommentResponses,
  StartNeuroshillingCampaignData,
  StartNeuroshillingCampaignErrors,
  StartNeuroshillingCampaignResponses,
  StartPhoneLoginData,
  StartPhoneLoginErrors,
  StartPhoneLoginResponses,
  StartWarmingData,
  StartWarmingErrors,
  StartWarmingResponses,
  StopNeurocommentData,
  StopNeurocommentErrors,
  StopNeurocommentResponses,
  StopNeuroshillingCampaignData,
  StopNeuroshillingCampaignErrors,
  StopNeuroshillingCampaignResponses,
  StopWarmingData,
  StopWarmingErrors,
  StopWarmingResponses,
  SubmitLoginCodeData,
  SubmitLoginCodeErrors,
  SubmitLoginCodeResponses,
  UnassignProxyData,
  UnassignProxyErrors,
  UnassignProxyResponses,
  UnpromoteFromNeurocommentData,
  UnpromoteFromNeurocommentErrors,
  UnpromoteFromNeurocommentResponses,
  UpdateAccountChannelData,
  UpdateAccountChannelErrors,
  UpdateAccountChannelResponses,
  UpdateAccountLimitsData,
  UpdateAccountLimitsErrors,
  UpdateAccountLimitsResponses,
  UpdateAccountProfileData,
  UpdateAccountProfileErrors,
  UpdateAccountProfileResponses,
  UpdateCampaignPromptData,
  UpdateCampaignPromptErrors,
  UpdateCampaignPromptResponses,
  UpdateNeurocommentSettingsData,
  UpdateNeurocommentSettingsErrors,
  UpdateNeurocommentSettingsResponses,
  UpdateNeuroshillingCampaignData,
  UpdateNeuroshillingCampaignErrors,
  UpdateNeuroshillingCampaignResponses,
  UpdateWarmingSettingsData,
  UpdateWarmingSettingsErrors,
  UpdateWarmingSettingsResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Login
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>,
): RequestResult<LoginResponses, LoginErrors, ThrowOnError> =>
  (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Logout
 */
export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>,
): RequestResult<LogoutResponses, LogoutErrors, ThrowOnError> =>
  (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({
    url: '/api/v1/auth/logout',
    ...options,
  });

/**
 * Me
 */
export const getMe = <ThrowOnError extends boolean = false>(
  options?: Options<GetMeData, ThrowOnError>,
): RequestResult<GetMeResponses, GetMeErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({
    url: '/api/v1/auth/me',
    ...options,
  });

/**
 * Health
 */
export const getHealth = <ThrowOnError extends boolean = false>(
  options?: Options<GetHealthData, ThrowOnError>,
): RequestResult<GetHealthResponses, GetHealthErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetHealthResponses, GetHealthErrors, ThrowOnError>({
    url: '/api/v1/health',
    ...options,
  });

/**
 * Ready
 *
 * Answer 503 while a dependency is down, so a supervisor can hold traffic back.
 *
 * The one route that answers a non-2xx with something other than the
 * ``ErrorEnvelope``, deliberately: this is consumed by an orchestrator's probe,
 * not the SPA, and the per-dependency verdict is the whole point of the body.
 * The status CODE has to carry the signal — a 200 saying "unavailable" is
 * invisible to every probe implementation.
 */
export const getReadiness = <ThrowOnError extends boolean = false>(
  options?: Options<GetReadinessData, ThrowOnError>,
): RequestResult<GetReadinessResponses, GetReadinessErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetReadinessResponses, GetReadinessErrors, ThrowOnError>({
    url: '/api/v1/ready',
    ...options,
  });

/**
 * List Accounts
 */
export const listAccounts = <ThrowOnError extends boolean = false>(
  options?: Options<ListAccountsData, ThrowOnError>,
): RequestResult<ListAccountsResponses, ListAccountsErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListAccountsResponses, ListAccountsErrors, ThrowOnError>({
    url: '/api/v1/accounts',
    ...options,
  });

/**
 * Account Stats
 *
 * Fleet-wide status counts for the Accounts page tiles (all pages, not one).
 */
export const accountStats = <ThrowOnError extends boolean = false>(
  options?: Options<AccountStatsData, ThrowOnError>,
): RequestResult<AccountStatsResponses, AccountStatsErrors, ThrowOnError> =>
  (options?.client ?? client).get<AccountStatsResponses, AccountStatsErrors, ThrowOnError>({
    url: '/api/v1/accounts/stats',
    ...options,
  });

/**
 * Check Account
 */
export const checkAccount = <ThrowOnError extends boolean = false>(
  options: Options<CheckAccountData, ThrowOnError>,
): RequestResult<CheckAccountResponses, CheckAccountErrors, ThrowOnError> =>
  (options.client ?? client).post<CheckAccountResponses, CheckAccountErrors, ThrowOnError>({
    url: '/api/v1/accounts/check',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Spam Check Account
 *
 * Re-probe @SpamBot for one account and return the fresh, cached verdict.
 */
export const spamCheckAccount = <ThrowOnError extends boolean = false>(
  options: Options<SpamCheckAccountData, ThrowOnError>,
): RequestResult<SpamCheckAccountResponses, SpamCheckAccountErrors, ThrowOnError> =>
  (options.client ?? client).post<SpamCheckAccountResponses, SpamCheckAccountErrors, ThrowOnError>({
    url: '/api/v1/accounts/{account_id}/spam-check',
    ...options,
  });

/**
 * Start Phone Login
 *
 * Create a new account from a bare phone number, ready for request-code.
 */
export const startPhoneLogin = <ThrowOnError extends boolean = false>(
  options: Options<StartPhoneLoginData, ThrowOnError>,
): RequestResult<StartPhoneLoginResponses, StartPhoneLoginErrors, ThrowOnError> =>
  (options.client ?? client).post<StartPhoneLoginResponses, StartPhoneLoginErrors, ThrowOnError>({
    url: '/api/v1/accounts/start-login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Request Login Code
 *
 * Send a Telegram login code to the account's phone (re-auth by code).
 */
export const requestLoginCode = <ThrowOnError extends boolean = false>(
  options: Options<RequestLoginCodeData, ThrowOnError>,
): RequestResult<RequestLoginCodeResponses, RequestLoginCodeErrors, ThrowOnError> =>
  (options.client ?? client).post<RequestLoginCodeResponses, RequestLoginCodeErrors, ThrowOnError>({
    url: '/api/v1/accounts/{account_id}/request-code',
    ...options,
  });

/**
 * Submit Login Code
 *
 * Complete sign-in with the SMS code (+ optional 2FA password).
 */
export const submitLoginCode = <ThrowOnError extends boolean = false>(
  options: Options<SubmitLoginCodeData, ThrowOnError>,
): RequestResult<SubmitLoginCodeResponses, SubmitLoginCodeErrors, ThrowOnError> =>
  (options.client ?? client).post<SubmitLoginCodeResponses, SubmitLoginCodeErrors, ThrowOnError>({
    url: '/api/v1/accounts/{account_id}/submit-code',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Logout Account
 *
 * Log the account out server-side and mark it unauthorized.
 */
export const logoutAccount = <ThrowOnError extends boolean = false>(
  options: Options<LogoutAccountData, ThrowOnError>,
): RequestResult<LogoutAccountResponses, LogoutAccountErrors, ThrowOnError> =>
  (options.client ?? client).post<LogoutAccountResponses, LogoutAccountErrors, ThrowOnError>({
    url: '/api/v1/accounts/{account_id}/logout',
    ...options,
  });

/**
 * Reset Account Session
 *
 * Log out and wipe the local session token so the next login is clean.
 */
export const resetAccountSession = <ThrowOnError extends boolean = false>(
  options: Options<ResetAccountSessionData, ThrowOnError>,
): RequestResult<ResetAccountSessionResponses, ResetAccountSessionErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ResetAccountSessionResponses,
    ResetAccountSessionErrors,
    ThrowOnError
  >({ url: '/api/v1/accounts/{account_id}/reset-session', ...options });

/**
 * Update Account Profile
 */
export const updateAccountProfile = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAccountProfileData, ThrowOnError>,
): RequestResult<UpdateAccountProfileResponses, UpdateAccountProfileErrors, ThrowOnError> =>
  (options.client ?? client).post<
    UpdateAccountProfileResponses,
    UpdateAccountProfileErrors,
    ThrowOnError
  >({
    url: '/api/v1/accounts/profile',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Account
 */
export const deleteAccount = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAccountData, ThrowOnError>,
): RequestResult<DeleteAccountResponses, DeleteAccountErrors, ThrowOnError> =>
  (options.client ?? client).delete<DeleteAccountResponses, DeleteAccountErrors, ThrowOnError>({
    url: '/api/v1/accounts/{account_id}',
    ...options,
  });

/**
 * Import Account Tdata
 */
export const importAccountTdata = <ThrowOnError extends boolean = false>(
  options: Options<ImportAccountTdataData, ThrowOnError>,
): RequestResult<ImportAccountTdataResponses, ImportAccountTdataErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ImportAccountTdataResponses,
    ImportAccountTdataErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: '/api/v1/accounts/import-tdata',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Import Account Session
 */
export const importAccountSession = <ThrowOnError extends boolean = false>(
  options: Options<ImportAccountSessionData, ThrowOnError>,
): RequestResult<ImportAccountSessionResponses, ImportAccountSessionErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ImportAccountSessionResponses,
    ImportAccountSessionErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: '/api/v1/accounts/import-session',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Set Account Photo
 */
export const setAccountPhoto = <ThrowOnError extends boolean = false>(
  options: Options<SetAccountPhotoData, ThrowOnError>,
): RequestResult<SetAccountPhotoResponses, SetAccountPhotoErrors, ThrowOnError> =>
  (options.client ?? client).post<SetAccountPhotoResponses, SetAccountPhotoErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/accounts/photo',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Resync Account Avatar
 *
 * Re-pull the accounts-table avatar from Telegram; answers the updated row.
 *
 * Call this ONCE after a photo batch: ``POST /accounts/photo`` uploads one file
 * per request, so re-syncing inside it would spend a ``get_me`` plus a thumb
 * download per photo when only the last one survives.
 */
export const resyncAccountAvatar = <ThrowOnError extends boolean = false>(
  options: Options<ResyncAccountAvatarData, ThrowOnError>,
): RequestResult<ResyncAccountAvatarResponses, ResyncAccountAvatarErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ResyncAccountAvatarResponses,
    ResyncAccountAvatarErrors,
    ThrowOnError
  >({ url: '/api/v1/accounts/{account_id}/avatar/resync', ...options });

/**
 * Get Account Profile Snapshot
 *
 * Live profile (name / bio / photos / stories / music) for the edit modal.
 *
 * ``refresh=true`` (the modal's «Обновить» button) bypasses the read cache and
 * re-pulls from Telegram.
 */
export const getAccountProfileSnapshot = <ThrowOnError extends boolean = false>(
  options: Options<GetAccountProfileSnapshotData, ThrowOnError>,
): RequestResult<
  GetAccountProfileSnapshotResponses,
  GetAccountProfileSnapshotErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetAccountProfileSnapshotResponses,
    GetAccountProfileSnapshotErrors,
    ThrowOnError
  >({ url: '/api/v1/accounts/{account_id}/profile-snapshot', ...options });

/**
 * Post Account Story
 */
export const postAccountStory = <ThrowOnError extends boolean = false>(
  options: Options<PostAccountStoryData, ThrowOnError>,
): RequestResult<PostAccountStoryResponses, PostAccountStoryErrors, ThrowOnError> =>
  (options.client ?? client).post<PostAccountStoryResponses, PostAccountStoryErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/accounts/{account_id}/story',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Add Account Music
 */
export const addAccountMusic = <ThrowOnError extends boolean = false>(
  options: Options<AddAccountMusicData, ThrowOnError>,
): RequestResult<AddAccountMusicResponses, AddAccountMusicErrors, ThrowOnError> =>
  (options.client ?? client).post<AddAccountMusicResponses, AddAccountMusicErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/accounts/{account_id}/music',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Remove Account Story
 */
export const removeAccountStory = <ThrowOnError extends boolean = false>(
  options: Options<RemoveAccountStoryData, ThrowOnError>,
): RequestResult<RemoveAccountStoryResponses, RemoveAccountStoryErrors, ThrowOnError> =>
  (options.client ?? client).post<
    RemoveAccountStoryResponses,
    RemoveAccountStoryErrors,
    ThrowOnError
  >({
    url: '/api/v1/accounts/{account_id}/story/remove',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Set Account Story Pinned
 */
export const setAccountStoryPinned = <ThrowOnError extends boolean = false>(
  options: Options<SetAccountStoryPinnedData, ThrowOnError>,
): RequestResult<SetAccountStoryPinnedResponses, SetAccountStoryPinnedErrors, ThrowOnError> =>
  (options.client ?? client).post<
    SetAccountStoryPinnedResponses,
    SetAccountStoryPinnedErrors,
    ThrowOnError
  >({
    url: '/api/v1/accounts/{account_id}/story/pin',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove Account Music
 */
export const removeAccountMusic = <ThrowOnError extends boolean = false>(
  options: Options<RemoveAccountMusicData, ThrowOnError>,
): RequestResult<RemoveAccountMusicResponses, RemoveAccountMusicErrors, ThrowOnError> =>
  (options.client ?? client).post<
    RemoveAccountMusicResponses,
    RemoveAccountMusicErrors,
    ThrowOnError
  >({
    url: '/api/v1/accounts/{account_id}/music/remove',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove Account Photo
 */
export const removeAccountPhoto = <ThrowOnError extends boolean = false>(
  options: Options<RemoveAccountPhotoData, ThrowOnError>,
): RequestResult<RemoveAccountPhotoResponses, RemoveAccountPhotoErrors, ThrowOnError> =>
  (options.client ?? client).post<
    RemoveAccountPhotoResponses,
    RemoveAccountPhotoErrors,
    ThrowOnError
  >({
    url: '/api/v1/accounts/{account_id}/photo/remove',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Set Account Photo Main
 */
export const setAccountPhotoMain = <ThrowOnError extends boolean = false>(
  options: Options<SetAccountPhotoMainData, ThrowOnError>,
): RequestResult<SetAccountPhotoMainResponses, SetAccountPhotoMainErrors, ThrowOnError> =>
  (options.client ?? client).post<
    SetAccountPhotoMainResponses,
    SetAccountPhotoMainErrors,
    ThrowOnError
  >({
    url: '/api/v1/accounts/{account_id}/photo/main',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Account Channels
 */
export const listAccountChannels = <ThrowOnError extends boolean = false>(
  options: Options<ListAccountChannelsData, ThrowOnError>,
): RequestResult<ListAccountChannelsResponses, ListAccountChannelsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ListAccountChannelsResponses,
    ListAccountChannelsErrors,
    ThrowOnError
  >({ url: '/api/v1/accounts/{account_id}/channels', ...options });

/**
 * Create Account Channel
 */
export const createAccountChannel = <ThrowOnError extends boolean = false>(
  options: Options<CreateAccountChannelData, ThrowOnError>,
): RequestResult<CreateAccountChannelResponses, CreateAccountChannelErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateAccountChannelResponses,
    CreateAccountChannelErrors,
    ThrowOnError
  >({
    url: '/api/v1/accounts/{account_id}/channels',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Check Account Channel Username
 */
export const checkAccountChannelUsername = <ThrowOnError extends boolean = false>(
  options: Options<CheckAccountChannelUsernameData, ThrowOnError>,
): RequestResult<
  CheckAccountChannelUsernameResponses,
  CheckAccountChannelUsernameErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    CheckAccountChannelUsernameResponses,
    CheckAccountChannelUsernameErrors,
    ThrowOnError
  >({ url: '/api/v1/accounts/{account_id}/channel-username-check', ...options });

/**
 * Get Account Channel
 */
export const getAccountChannel = <ThrowOnError extends boolean = false>(
  options: Options<GetAccountChannelData, ThrowOnError>,
): RequestResult<GetAccountChannelResponses, GetAccountChannelErrors, ThrowOnError> =>
  (options.client ?? client).get<GetAccountChannelResponses, GetAccountChannelErrors, ThrowOnError>(
    { url: '/api/v1/accounts/{account_id}/channels/{channel_id}', ...options },
  );

/**
 * Update Account Channel
 */
export const updateAccountChannel = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAccountChannelData, ThrowOnError>,
): RequestResult<UpdateAccountChannelResponses, UpdateAccountChannelErrors, ThrowOnError> =>
  (options.client ?? client).post<
    UpdateAccountChannelResponses,
    UpdateAccountChannelErrors,
    ThrowOnError
  >({
    url: '/api/v1/accounts/{account_id}/channels/{channel_id}/update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Set Account Channel Photo
 */
export const setAccountChannelPhoto = <ThrowOnError extends boolean = false>(
  options: Options<SetAccountChannelPhotoData, ThrowOnError>,
): RequestResult<SetAccountChannelPhotoResponses, SetAccountChannelPhotoErrors, ThrowOnError> =>
  (options.client ?? client).post<
    SetAccountChannelPhotoResponses,
    SetAccountChannelPhotoErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: '/api/v1/accounts/{account_id}/channels/{channel_id}/photo',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Delete Account Channel
 */
export const deleteAccountChannel = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAccountChannelData, ThrowOnError>,
): RequestResult<DeleteAccountChannelResponses, DeleteAccountChannelErrors, ThrowOnError> =>
  (options.client ?? client).post<
    DeleteAccountChannelResponses,
    DeleteAccountChannelErrors,
    ThrowOnError
  >({ url: '/api/v1/accounts/{account_id}/channels/{channel_id}/delete', ...options });

/**
 * List Account Channel Posts
 */
export const listAccountChannelPosts = <ThrowOnError extends boolean = false>(
  options: Options<ListAccountChannelPostsData, ThrowOnError>,
): RequestResult<ListAccountChannelPostsResponses, ListAccountChannelPostsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ListAccountChannelPostsResponses,
    ListAccountChannelPostsErrors,
    ThrowOnError
  >({ url: '/api/v1/accounts/{account_id}/channels/{channel_id}/posts', ...options });

/**
 * Publish Account Channel Post
 */
export const publishAccountChannelPost = <ThrowOnError extends boolean = false>(
  options: Options<PublishAccountChannelPostData, ThrowOnError>,
): RequestResult<
  PublishAccountChannelPostResponses,
  PublishAccountChannelPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PublishAccountChannelPostResponses,
    PublishAccountChannelPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: '/api/v1/accounts/{account_id}/channels/{channel_id}/posts',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Edit Account Channel Post
 */
export const editAccountChannelPost = <ThrowOnError extends boolean = false>(
  options: Options<EditAccountChannelPostData, ThrowOnError>,
): RequestResult<EditAccountChannelPostResponses, EditAccountChannelPostErrors, ThrowOnError> =>
  (options.client ?? client).post<
    EditAccountChannelPostResponses,
    EditAccountChannelPostErrors,
    ThrowOnError
  >({
    url: '/api/v1/accounts/{account_id}/channels/{channel_id}/posts/{post_id}/edit',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Account Channel Post
 */
export const deleteAccountChannelPost = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAccountChannelPostData, ThrowOnError>,
): RequestResult<DeleteAccountChannelPostResponses, DeleteAccountChannelPostErrors, ThrowOnError> =>
  (options.client ?? client).post<
    DeleteAccountChannelPostResponses,
    DeleteAccountChannelPostErrors,
    ThrowOnError
  >({
    url: '/api/v1/accounts/{account_id}/channels/{channel_id}/posts/{post_id}/delete',
    ...options,
  });

/**
 * Get Account Privacy
 *
 * Live Profile photo / Bio / Last seen privacy levels for one account.
 */
export const getAccountPrivacy = <ThrowOnError extends boolean = false>(
  options: Options<GetAccountPrivacyData, ThrowOnError>,
): RequestResult<GetAccountPrivacyResponses, GetAccountPrivacyErrors, ThrowOnError> =>
  (options.client ?? client).get<GetAccountPrivacyResponses, GetAccountPrivacyErrors, ThrowOnError>(
    { url: '/api/v1/accounts/{account_id}/privacy', ...options },
  );

/**
 * Set Account Privacy
 *
 * Apply the given keys, then answer with the re-read state (one round trip).
 */
export const setAccountPrivacy = <ThrowOnError extends boolean = false>(
  options: Options<SetAccountPrivacyData, ThrowOnError>,
): RequestResult<SetAccountPrivacyResponses, SetAccountPrivacyErrors, ThrowOnError> =>
  (options.client ?? client).put<SetAccountPrivacyResponses, SetAccountPrivacyErrors, ThrowOnError>(
    {
      url: '/api/v1/accounts/{account_id}/privacy',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    },
  );

/**
 * Set All Accounts Privacy
 *
 * Apply the same keys to every account; unusable sessions come back skipped.
 */
export const setAllAccountsPrivacy = <ThrowOnError extends boolean = false>(
  options: Options<SetAllAccountsPrivacyData, ThrowOnError>,
): RequestResult<SetAllAccountsPrivacyResponses, SetAllAccountsPrivacyErrors, ThrowOnError> =>
  (options.client ?? client).post<
    SetAllAccountsPrivacyResponses,
    SetAllAccountsPrivacyErrors,
    ThrowOnError
  >({
    url: '/api/v1/accounts/privacy/all',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove Account Twofa
 *
 * Turn 2FA off using the stored password, then answer with the re-read state.
 *
 * ``?forget_only=true`` drops the dashboard's copy of the password and spends no
 * RPC at all. It is the only way out of every state in which the column holds a
 * password Telegram does not accept — a rollback whose UPDATE failed, a process
 * death mid-write, a lost answer over a live read that also failed — each of which
 * is otherwise terminal, because something IS stored so the not-stored guard can
 * never fire again. It is a query flag rather than an inference because only the
 * operator can tell a worthless stored value from a working one.
 */
export const removeAccountTwofa = <ThrowOnError extends boolean = false>(
  options: Options<RemoveAccountTwofaData, ThrowOnError>,
): RequestResult<RemoveAccountTwofaResponses, RemoveAccountTwofaErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    RemoveAccountTwofaResponses,
    RemoveAccountTwofaErrors,
    ThrowOnError
  >({ url: '/api/v1/accounts/{account_id}/2fa', ...options });

/**
 * Get Account Twofa
 *
 * Live cloud-password state for one account — booleans and the public hint.
 */
export const getAccountTwofa = <ThrowOnError extends boolean = false>(
  options: Options<GetAccountTwofaData, ThrowOnError>,
): RequestResult<GetAccountTwofaResponses, GetAccountTwofaErrors, ThrowOnError> =>
  (options.client ?? client).get<GetAccountTwofaResponses, GetAccountTwofaErrors, ThrowOnError>({
    url: '/api/v1/accounts/{account_id}/2fa',
    ...options,
  });

/**
 * Set Account Twofa
 *
 * Set or change the cloud password; the response is the only copy handed out.
 *
 * ``no-store`` on the one response in this API that carries a plaintext
 * credential. A POST response is already non-cacheable per RFC 9111, so this is a
 * belt for any reverse proxy in front of the app, set through the injected
 * ``Response`` the auth cookies and ``GET /ready`` already use.
 */
export const setAccountTwofa = <ThrowOnError extends boolean = false>(
  options: Options<SetAccountTwofaData, ThrowOnError>,
): RequestResult<SetAccountTwofaResponses, SetAccountTwofaErrors, ThrowOnError> =>
  (options.client ?? client).post<SetAccountTwofaResponses, SetAccountTwofaErrors, ThrowOnError>({
    url: '/api/v1/accounts/{account_id}/2fa',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Cancel Account Twofa Email
 *
 * Abandon a pending recovery email; the cloud password stays as it is.
 */
export const cancelAccountTwofaEmail = <ThrowOnError extends boolean = false>(
  options: Options<CancelAccountTwofaEmailData, ThrowOnError>,
): RequestResult<CancelAccountTwofaEmailResponses, CancelAccountTwofaEmailErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    CancelAccountTwofaEmailResponses,
    CancelAccountTwofaEmailErrors,
    ThrowOnError
  >({ url: '/api/v1/accounts/{account_id}/2fa/email', ...options });

/**
 * Set Account Twofa Email
 *
 * Attach a recovery email; the response says whether a code was mailed.
 */
export const setAccountTwofaEmail = <ThrowOnError extends boolean = false>(
  options: Options<SetAccountTwofaEmailData, ThrowOnError>,
): RequestResult<SetAccountTwofaEmailResponses, SetAccountTwofaEmailErrors, ThrowOnError> =>
  (options.client ?? client).post<
    SetAccountTwofaEmailResponses,
    SetAccountTwofaEmailErrors,
    ThrowOnError
  >({
    url: '/api/v1/accounts/{account_id}/2fa/email',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Confirm Account Twofa Email
 *
 * Confirm the pending recovery email with the code from the letter.
 */
export const confirmAccountTwofaEmail = <ThrowOnError extends boolean = false>(
  options: Options<ConfirmAccountTwofaEmailData, ThrowOnError>,
): RequestResult<ConfirmAccountTwofaEmailResponses, ConfirmAccountTwofaEmailErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ConfirmAccountTwofaEmailResponses,
    ConfirmAccountTwofaEmailErrors,
    ThrowOnError
  >({
    url: '/api/v1/accounts/{account_id}/2fa/email/confirm',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Resend Account Twofa Email
 *
 * Mail the confirmation code again for an email that is still pending.
 */
export const resendAccountTwofaEmail = <ThrowOnError extends boolean = false>(
  options: Options<ResendAccountTwofaEmailData, ThrowOnError>,
): RequestResult<ResendAccountTwofaEmailResponses, ResendAccountTwofaEmailErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ResendAccountTwofaEmailResponses,
    ResendAccountTwofaEmailErrors,
    ThrowOnError
  >({ url: '/api/v1/accounts/{account_id}/2fa/email/resend', ...options });

/**
 * Clear Account Twofa Email
 *
 * Detach a CONFIRMED recovery email; the cloud password stays as it is.
 *
 * A separate route from ``DELETE .../2fa/email`` because the two are separate
 * Telegram calls: that one cancels a verification still in flight, this one clears
 * an address Telegram already accepted. Nothing but
 * ``account.updatePasswordSettings`` with an empty ``email`` can do the second.
 */
export const clearAccountTwofaEmail = <ThrowOnError extends boolean = false>(
  options: Options<ClearAccountTwofaEmailData, ThrowOnError>,
): RequestResult<ClearAccountTwofaEmailResponses, ClearAccountTwofaEmailErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    ClearAccountTwofaEmailResponses,
    ClearAccountTwofaEmailErrors,
    ThrowOnError
  >({ url: '/api/v1/accounts/{account_id}/2fa/email/recovery', ...options });

/**
 * List Proxies
 */
export const listProxies = <ThrowOnError extends boolean = false>(
  options?: Options<ListProxiesData, ThrowOnError>,
): RequestResult<ListProxiesResponses, ListProxiesErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListProxiesResponses, ListProxiesErrors, ThrowOnError>({
    url: '/api/v1/proxies',
    ...options,
  });

/**
 * Create Proxy
 */
export const createProxy = <ThrowOnError extends boolean = false>(
  options: Options<CreateProxyData, ThrowOnError>,
): RequestResult<CreateProxyResponses, CreateProxyErrors, ThrowOnError> =>
  (options.client ?? client).post<CreateProxyResponses, CreateProxyErrors, ThrowOnError>({
    url: '/api/v1/proxies',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Probe Proxy
 */
export const probeProxy = <ThrowOnError extends boolean = false>(
  options: Options<ProbeProxyData, ThrowOnError>,
): RequestResult<ProbeProxyResponses, ProbeProxyErrors, ThrowOnError> =>
  (options.client ?? client).post<ProbeProxyResponses, ProbeProxyErrors, ThrowOnError>({
    url: '/api/v1/proxies/probe',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Check Proxy
 */
export const checkProxy = <ThrowOnError extends boolean = false>(
  options: Options<CheckProxyData, ThrowOnError>,
): RequestResult<CheckProxyResponses, CheckProxyErrors, ThrowOnError> =>
  (options.client ?? client).post<CheckProxyResponses, CheckProxyErrors, ThrowOnError>({
    url: '/api/v1/proxies/{proxy_id}/check',
    ...options,
  });

/**
 * Assign Proxy
 */
export const assignProxy = <ThrowOnError extends boolean = false>(
  options: Options<AssignProxyData, ThrowOnError>,
): RequestResult<AssignProxyResponses, AssignProxyErrors, ThrowOnError> =>
  (options.client ?? client).post<AssignProxyResponses, AssignProxyErrors, ThrowOnError>({
    url: '/api/v1/proxies/{proxy_id}/assign',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Unassign Proxy
 */
export const unassignProxy = <ThrowOnError extends boolean = false>(
  options: Options<UnassignProxyData, ThrowOnError>,
): RequestResult<UnassignProxyResponses, UnassignProxyErrors, ThrowOnError> =>
  (options.client ?? client).post<UnassignProxyResponses, UnassignProxyErrors, ThrowOnError>({
    url: '/api/v1/proxies/unassign',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Proxy
 */
export const deleteProxy = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProxyData, ThrowOnError>,
): RequestResult<DeleteProxyResponses, DeleteProxyErrors, ThrowOnError> =>
  (options.client ?? client).delete<DeleteProxyResponses, DeleteProxyErrors, ThrowOnError>({
    url: '/api/v1/proxies/{proxy_id}',
    ...options,
  });

/**
 * Get Warming Board
 */
export const getWarmingBoard = <ThrowOnError extends boolean = false>(
  options?: Options<GetWarmingBoardData, ThrowOnError>,
): RequestResult<GetWarmingBoardResponses, GetWarmingBoardErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetWarmingBoardResponses, GetWarmingBoardErrors, ThrowOnError>({
    url: '/api/v1/warming/board',
    ...options,
  });

/**
 * Get Warmed Accounts
 *
 * Operator-graduated accounts (the warming page's "Прогретые аккаунты" card).
 */
export const listWarmedAccounts = <ThrowOnError extends boolean = false>(
  options?: Options<ListWarmedAccountsData, ThrowOnError>,
): RequestResult<ListWarmedAccountsResponses, ListWarmedAccountsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListWarmedAccountsResponses,
    ListWarmedAccountsErrors,
    ThrowOnError
  >({ url: '/api/v1/warming/warmed', ...options });

/**
 * Promote Account
 *
 * Graduate an account: stop warming + flag it for the neurocomment pool.
 */
export const promoteToNeurocomment = <ThrowOnError extends boolean = false>(
  options: Options<PromoteToNeurocommentData, ThrowOnError>,
): RequestResult<PromoteToNeurocommentResponses, PromoteToNeurocommentErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PromoteToNeurocommentResponses,
    PromoteToNeurocommentErrors,
    ThrowOnError
  >({
    url: '/api/v1/warming/promote',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Handoff Account
 *
 * Second stage: move a warmed-card account into the neurocomment idle pool.
 */
export const handoffToNeurocomment = <ThrowOnError extends boolean = false>(
  options: Options<HandoffToNeurocommentData, ThrowOnError>,
): RequestResult<HandoffToNeurocommentResponses, HandoffToNeurocommentErrors, ThrowOnError> =>
  (options.client ?? client).post<
    HandoffToNeurocommentResponses,
    HandoffToNeurocommentErrors,
    ThrowOnError
  >({
    url: '/api/v1/warming/handoff',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Unpromote Account
 *
 * Reverse a graduation: clear the promotion flag (the warmed card's «вернуть»).
 */
export const unpromoteFromNeurocomment = <ThrowOnError extends boolean = false>(
  options: Options<UnpromoteFromNeurocommentData, ThrowOnError>,
): RequestResult<
  UnpromoteFromNeurocommentResponses,
  UnpromoteFromNeurocommentErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    UnpromoteFromNeurocommentResponses,
    UnpromoteFromNeurocommentErrors,
    ThrowOnError
  >({
    url: '/api/v1/warming/unpromote',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Start Warming
 */
export const startWarming = <ThrowOnError extends boolean = false>(
  options: Options<StartWarmingData, ThrowOnError>,
): RequestResult<StartWarmingResponses, StartWarmingErrors, ThrowOnError> =>
  (options.client ?? client).post<StartWarmingResponses, StartWarmingErrors, ThrowOnError>({
    url: '/api/v1/warming/start',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Stop Warming
 */
export const stopWarming = <ThrowOnError extends boolean = false>(
  options: Options<StopWarmingData, ThrowOnError>,
): RequestResult<StopWarmingResponses, StopWarmingErrors, ThrowOnError> =>
  (options.client ?? client).post<StopWarmingResponses, StopWarmingErrors, ThrowOnError>({
    url: '/api/v1/warming/stop',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Warming Channels
 */
export const listWarmingChannels = <ThrowOnError extends boolean = false>(
  options?: Options<ListWarmingChannelsData, ThrowOnError>,
): RequestResult<ListWarmingChannelsResponses, ListWarmingChannelsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListWarmingChannelsResponses,
    ListWarmingChannelsErrors,
    ThrowOnError
  >({ url: '/api/v1/warming/channels', ...options });

/**
 * Add Warming Channels
 */
export const addWarmingChannels = <ThrowOnError extends boolean = false>(
  options: Options<AddWarmingChannelsData, ThrowOnError>,
): RequestResult<AddWarmingChannelsResponses, AddWarmingChannelsErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AddWarmingChannelsResponses,
    AddWarmingChannelsErrors,
    ThrowOnError
  >({
    url: '/api/v1/warming/channels',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove Warming Channel
 */
export const removeWarmingChannel = <ThrowOnError extends boolean = false>(
  options: Options<RemoveWarmingChannelData, ThrowOnError>,
): RequestResult<RemoveWarmingChannelResponses, RemoveWarmingChannelErrors, ThrowOnError> =>
  (options.client ?? client).post<
    RemoveWarmingChannelResponses,
    RemoveWarmingChannelErrors,
    ThrowOnError
  >({
    url: '/api/v1/warming/channels/remove',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Warming Settings
 */
export const getWarmingSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetWarmingSettingsData, ThrowOnError>,
): RequestResult<GetWarmingSettingsResponses, GetWarmingSettingsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetWarmingSettingsResponses,
    GetWarmingSettingsErrors,
    ThrowOnError
  >({ url: '/api/v1/warming/settings', ...options });

/**
 * Update Warming Settings
 */
export const updateWarmingSettings = <ThrowOnError extends boolean = false>(
  options: Options<UpdateWarmingSettingsData, ThrowOnError>,
): RequestResult<UpdateWarmingSettingsResponses, UpdateWarmingSettingsErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateWarmingSettingsResponses,
    UpdateWarmingSettingsErrors,
    ThrowOnError
  >({
    url: '/api/v1/warming/settings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Warming Dialogues
 *
 * Recent inter-account warming messages, newest first, for the live feed.
 */
export const listWarmingDialogues = <ThrowOnError extends boolean = false>(
  options?: Options<ListWarmingDialoguesData, ThrowOnError>,
): RequestResult<ListWarmingDialoguesResponses, ListWarmingDialoguesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListWarmingDialoguesResponses,
    ListWarmingDialoguesErrors,
    ThrowOnError
  >({ url: '/api/v1/warming/dialogues', ...options });

/**
 * Start Discovery
 */
export const startCampaignDiscovery = <ThrowOnError extends boolean = false>(
  options: Options<StartCampaignDiscoveryData, ThrowOnError>,
): RequestResult<StartCampaignDiscoveryResponses, StartCampaignDiscoveryErrors, ThrowOnError> =>
  (options.client ?? client).post<
    StartCampaignDiscoveryResponses,
    StartCampaignDiscoveryErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/campaigns/{campaign_id}/discovery/search',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Discovery
 */
export const getCampaignDiscovery = <ThrowOnError extends boolean = false>(
  options: Options<GetCampaignDiscoveryData, ThrowOnError>,
): RequestResult<GetCampaignDiscoveryResponses, GetCampaignDiscoveryErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetCampaignDiscoveryResponses,
    GetCampaignDiscoveryErrors,
    ThrowOnError
  >({ url: '/api/v1/neurocomment/campaigns/{campaign_id}/discovery', ...options });

/**
 * Adopt Discovery
 */
export const adoptCampaignDiscovery = <ThrowOnError extends boolean = false>(
  options: Options<AdoptCampaignDiscoveryData, ThrowOnError>,
): RequestResult<AdoptCampaignDiscoveryResponses, AdoptCampaignDiscoveryErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AdoptCampaignDiscoveryResponses,
    AdoptCampaignDiscoveryErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/campaigns/{campaign_id}/discovery/adopt',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Expand Discovery Keywords
 *
 * Widen one typed topic into search keywords. Not campaign-scoped, hence no id.
 *
 * Never fails on the LLM's behalf: an unusable answer is a 200 carrying a short
 * ``error`` code, because the operator's next move (type the keywords by hand) is
 * the same either way and a toast-worthy 5xx would only imply the board is broken.
 */
export const expandDiscoveryKeywords = <ThrowOnError extends boolean = false>(
  options: Options<ExpandDiscoveryKeywordsData, ThrowOnError>,
): RequestResult<ExpandDiscoveryKeywordsResponses, ExpandDiscoveryKeywordsErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ExpandDiscoveryKeywordsResponses,
    ExpandDiscoveryKeywordsErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/discovery/keywords',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Campaigns
 */
export const listCampaigns = <ThrowOnError extends boolean = false>(
  options?: Options<ListCampaignsData, ThrowOnError>,
): RequestResult<ListCampaignsResponses, ListCampaignsErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListCampaignsResponses, ListCampaignsErrors, ThrowOnError>({
    url: '/api/v1/neurocomment/campaigns',
    ...options,
  });

/**
 * Create Campaign
 */
export const createCampaign = <ThrowOnError extends boolean = false>(
  options: Options<CreateCampaignData, ThrowOnError>,
): RequestResult<CreateCampaignResponses, CreateCampaignErrors, ThrowOnError> =>
  (options.client ?? client).post<CreateCampaignResponses, CreateCampaignErrors, ThrowOnError>({
    url: '/api/v1/neurocomment/campaigns',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Board
 */
export const getNeurocommentBoard = <ThrowOnError extends boolean = false>(
  options: Options<GetNeurocommentBoardData, ThrowOnError>,
): RequestResult<GetNeurocommentBoardResponses, GetNeurocommentBoardErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetNeurocommentBoardResponses,
    GetNeurocommentBoardErrors,
    ThrowOnError
  >({ url: '/api/v1/neurocomment/campaigns/{campaign_id}/board', ...options });

/**
 * Check Channel Bans
 *
 * Live-probe each campaign channel for account bans (the "Проверить каналы" button).
 */
export const checkCampaignChannelBans = <ThrowOnError extends boolean = false>(
  options: Options<CheckCampaignChannelBansData, ThrowOnError>,
): RequestResult<CheckCampaignChannelBansResponses, CheckCampaignChannelBansErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CheckCampaignChannelBansResponses,
    CheckCampaignChannelBansErrors,
    ThrowOnError
  >({ url: '/api/v1/neurocomment/campaigns/{campaign_id}/channel-bans', ...options });

/**
 * List Comments
 *
 * One cursor page of a campaign's posted comments (newest first) — the history modal.
 */
export const listNeurocommentComments = <ThrowOnError extends boolean = false>(
  options: Options<ListNeurocommentCommentsData, ThrowOnError>,
): RequestResult<ListNeurocommentCommentsResponses, ListNeurocommentCommentsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ListNeurocommentCommentsResponses,
    ListNeurocommentCommentsErrors,
    ThrowOnError
  >({ url: '/api/v1/neurocomment/campaigns/{campaign_id}/comments', ...options });

/**
 * Link Channel
 */
export const linkCampaignChannel = <ThrowOnError extends boolean = false>(
  options: Options<LinkCampaignChannelData, ThrowOnError>,
): RequestResult<LinkCampaignChannelResponses, LinkCampaignChannelErrors, ThrowOnError> =>
  (options.client ?? client).post<
    LinkCampaignChannelResponses,
    LinkCampaignChannelErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/campaigns/{campaign_id}/channels',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Assign Account
 */
export const assignCampaignAccount = <ThrowOnError extends boolean = false>(
  options: Options<AssignCampaignAccountData, ThrowOnError>,
): RequestResult<AssignCampaignAccountResponses, AssignCampaignAccountErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AssignCampaignAccountResponses,
    AssignCampaignAccountErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/campaigns/{campaign_id}/accounts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove Account
 */
export const removeCampaignAccount = <ThrowOnError extends boolean = false>(
  options: Options<RemoveCampaignAccountData, ThrowOnError>,
): RequestResult<RemoveCampaignAccountResponses, RemoveCampaignAccountErrors, ThrowOnError> =>
  (options.client ?? client).post<
    RemoveCampaignAccountResponses,
    RemoveCampaignAccountErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/campaigns/{campaign_id}/accounts/remove',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Set Account Channel
 *
 * Set a campaign account's channel subset (empty ``channels`` = all channels).
 *
 * An account with a non-empty subset comments only on those channels; an empty
 * subset serves all campaign channels. Returns the refreshed board so the SPA
 * re-renders the card.
 */
export const setCampaignAccountChannel = <ThrowOnError extends boolean = false>(
  options: Options<SetCampaignAccountChannelData, ThrowOnError>,
): RequestResult<
  SetCampaignAccountChannelResponses,
  SetCampaignAccountChannelErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    SetCampaignAccountChannelResponses,
    SetCampaignAccountChannelErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/campaigns/{campaign_id}/accounts/{account_id}/channel',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Campaign
 *
 * Delete a campaign and all its serving links, channels, and comments.
 */
export const deleteCampaign = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCampaignData, ThrowOnError>,
): RequestResult<DeleteCampaignResponses, DeleteCampaignErrors, ThrowOnError> =>
  (options.client ?? client).delete<DeleteCampaignResponses, DeleteCampaignErrors, ThrowOnError>({
    url: '/api/v1/neurocomment/campaigns/{campaign_id}',
    ...options,
  });

/**
 * Remove Channel
 *
 * Detach a channel from a campaign (frees its slot for another campaign).
 */
export const removeCampaignChannel = <ThrowOnError extends boolean = false>(
  options: Options<RemoveCampaignChannelData, ThrowOnError>,
): RequestResult<RemoveCampaignChannelResponses, RemoveCampaignChannelErrors, ThrowOnError> =>
  (options.client ?? client).post<
    RemoveCampaignChannelResponses,
    RemoveCampaignChannelErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/campaigns/{campaign_id}/channels/remove',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update Prompt
 *
 * Replace a campaign's generation prompt (the edit-prompt modal).
 */
export const updateCampaignPrompt = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCampaignPromptData, ThrowOnError>,
): RequestResult<UpdateCampaignPromptResponses, UpdateCampaignPromptErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateCampaignPromptResponses,
    UpdateCampaignPromptErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/campaigns/{campaign_id}/prompt',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Set Campaign Solver
 *
 * Turn the campaign's challenge (captcha) solver on/off.
 */
export const setCampaignSolver = <ThrowOnError extends boolean = false>(
  options: Options<SetCampaignSolverData, ThrowOnError>,
): RequestResult<SetCampaignSolverResponses, SetCampaignSolverErrors, ThrowOnError> =>
  (options.client ?? client).post<
    SetCampaignSolverResponses,
    SetCampaignSolverErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/campaigns/{campaign_id}/solver',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Campaign Challenges
 *
 * Recent unsolved bot-challenges across the campaign's channels (captcha queue).
 */
export const listCampaignChallenges = <ThrowOnError extends boolean = false>(
  options: Options<ListCampaignChallengesData, ThrowOnError>,
): RequestResult<ListCampaignChallengesResponses, ListCampaignChallengesErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ListCampaignChallengesResponses,
    ListCampaignChallengesErrors,
    ThrowOnError
  >({ url: '/api/v1/neurocomment/campaigns/{campaign_id}/challenges', ...options });

/**
 * Count Campaign Challenge Outcomes
 *
 * Challenge-outcome counters (solved/failed/give_up/pending) across a campaign (#148).
 */
export const countCampaignChallengeOutcomes = <ThrowOnError extends boolean = false>(
  options: Options<CountCampaignChallengeOutcomesData, ThrowOnError>,
): RequestResult<
  CountCampaignChallengeOutcomesResponses,
  CountCampaignChallengeOutcomesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    CountCampaignChallengeOutcomesResponses,
    CountCampaignChallengeOutcomesErrors,
    ThrowOnError
  >({ url: '/api/v1/neurocomment/campaigns/{campaign_id}/challenges/counts', ...options });

/**
 * List Channel Challenges
 *
 * Recent unsolved bot-challenges for one channel — the work-view drill-down (#148).
 */
export const listChannelChallenges = <ThrowOnError extends boolean = false>(
  options: Options<ListChannelChallengesData, ThrowOnError>,
): RequestResult<ListChannelChallengesResponses, ListChannelChallengesErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ListChannelChallengesResponses,
    ListChannelChallengesErrors,
    ThrowOnError
  >({ url: '/api/v1/neurocomment/channels/challenges', ...options });

/**
 * Skip Pair
 *
 * Operator "Skip channel for this account": the engine never selects the pair (#148).
 */
export const skipNeurocommentPair = <ThrowOnError extends boolean = false>(
  options: Options<SkipNeurocommentPairData, ThrowOnError>,
): RequestResult<SkipNeurocommentPairResponses, SkipNeurocommentPairErrors, ThrowOnError> =>
  (options.client ?? client).post<
    SkipNeurocommentPairResponses,
    SkipNeurocommentPairErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/skip',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Set Campaign Status
 *
 * Per-campaign run/pause: flip a campaign between active and paused (#148).
 */
export const setCampaignStatus = <ThrowOnError extends boolean = false>(
  options: Options<SetCampaignStatusData, ThrowOnError>,
): RequestResult<SetCampaignStatusResponses, SetCampaignStatusErrors, ThrowOnError> =>
  (options.client ?? client).post<
    SetCampaignStatusResponses,
    SetCampaignStatusErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/campaigns/{campaign_id}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Runtime
 */
export const getNeurocommentRuntime = <ThrowOnError extends boolean = false>(
  options?: Options<GetNeurocommentRuntimeData, ThrowOnError>,
): RequestResult<GetNeurocommentRuntimeResponses, GetNeurocommentRuntimeErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetNeurocommentRuntimeResponses,
    GetNeurocommentRuntimeErrors,
    ThrowOnError
  >({ url: '/api/v1/neurocomment/runtime', ...options });

/**
 * Start
 */
export const startNeurocomment = <ThrowOnError extends boolean = false>(
  options: Options<StartNeurocommentData, ThrowOnError>,
): RequestResult<StartNeurocommentResponses, StartNeurocommentErrors, ThrowOnError> =>
  (options.client ?? client).post<
    StartNeurocommentResponses,
    StartNeurocommentErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/start',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Stop
 *
 * Pause the runtime: unsubscribe but keep the remembered listener account.
 */
export const stopNeurocomment = <ThrowOnError extends boolean = false>(
  options?: Options<StopNeurocommentData, ThrowOnError>,
): RequestResult<StopNeurocommentResponses, StopNeurocommentErrors, ThrowOnError> =>
  (options?.client ?? client).post<StopNeurocommentResponses, StopNeurocommentErrors, ThrowOnError>(
    { url: '/api/v1/neurocomment/stop', ...options },
  );

/**
 * Set Listener
 *
 * Remember the picked listener without starting the engine ("Сохранить" in the modal).
 */
export const setNeurocommentListener = <ThrowOnError extends boolean = false>(
  options: Options<SetNeurocommentListenerData, ThrowOnError>,
): RequestResult<SetNeurocommentListenerResponses, SetNeurocommentListenerErrors, ThrowOnError> =>
  (options.client ?? client).post<
    SetNeurocommentListenerResponses,
    SetNeurocommentListenerErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/listener',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Clear Listener
 *
 * Remove the listener ("снять слушателя"): unsubscribe and forget the account.
 */
export const clearNeurocommentListener = <ThrowOnError extends boolean = false>(
  options?: Options<ClearNeurocommentListenerData, ThrowOnError>,
): RequestResult<
  ClearNeurocommentListenerResponses,
  ClearNeurocommentListenerErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    ClearNeurocommentListenerResponses,
    ClearNeurocommentListenerErrors,
    ThrowOnError
  >({ url: '/api/v1/neurocomment/listener/clear', ...options });

/**
 * Get Settings
 */
export const getNeurocommentSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetNeurocommentSettingsData, ThrowOnError>,
): RequestResult<GetNeurocommentSettingsResponses, GetNeurocommentSettingsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetNeurocommentSettingsResponses,
    GetNeurocommentSettingsErrors,
    ThrowOnError
  >({ url: '/api/v1/neurocomment/settings', ...options });

/**
 * Update Settings
 */
export const updateNeurocommentSettings = <ThrowOnError extends boolean = false>(
  options: Options<UpdateNeurocommentSettingsData, ThrowOnError>,
): RequestResult<
  UpdateNeurocommentSettingsResponses,
  UpdateNeurocommentSettingsErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateNeurocommentSettingsResponses,
    UpdateNeurocommentSettingsErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/settings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Account Limits
 *
 * One account's caps, what each window has spent, and when a slot comes back.
 */
export const getAccountLimits = <ThrowOnError extends boolean = false>(
  options: Options<GetAccountLimitsData, ThrowOnError>,
): RequestResult<GetAccountLimitsResponses, GetAccountLimitsErrors, ThrowOnError> =>
  (options.client ?? client).get<GetAccountLimitsResponses, GetAccountLimitsErrors, ThrowOnError>({
    url: '/api/v1/neurocomment/accounts/{account_id}/limits',
    ...options,
  });

/**
 * Update Account Limits
 *
 * Replace the account's overrides — a null field drops back to the fleet cap.
 */
export const updateAccountLimits = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAccountLimitsData, ThrowOnError>,
): RequestResult<UpdateAccountLimitsResponses, UpdateAccountLimitsErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateAccountLimitsResponses,
    UpdateAccountLimitsErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/accounts/{account_id}/limits',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Logs
 *
 * Clear log rows whose event starts with any of the comma-separated ``event_prefix`` values.
 *
 * Only omitting ``event_prefix``, or passing the empty string, clears every row; a value
 * that yields no usable prefix (``" "``, ``","``) clears nothing.
 */
export const clearLogs = <ThrowOnError extends boolean = false>(
  options?: Options<ClearLogsData, ThrowOnError>,
): RequestResult<ClearLogsResponses, ClearLogsErrors, ThrowOnError> =>
  (options?.client ?? client).delete<ClearLogsResponses, ClearLogsErrors, ThrowOnError>({
    url: '/api/v1/logs',
    ...options,
  });

/**
 * List Logs
 *
 * List log rows, newest first.
 *
 * ``event_prefix`` accepts a comma-separated list of prefixes and keeps rows whose
 * event starts with any of them (e.g. ``warming_,spam_status``). Omitting it, or passing
 * the empty string, applies no filter; a value that yields no usable prefix (``" "``,
 * ``","``) is still a filter and matches nothing.
 */
export const listLogs = <ThrowOnError extends boolean = false>(
  options?: Options<ListLogsData, ThrowOnError>,
): RequestResult<ListLogsResponses, ListLogsErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListLogsResponses, ListLogsErrors, ThrowOnError>({
    url: '/api/v1/logs',
    ...options,
  });

/**
 * Count Logs
 *
 * Count the rows ``DELETE /logs`` would remove for the same ``event_prefix``.
 *
 * Read before the confirmation prompt: a page of rows is no guide to the size of
 * the purge. Matching is the delete's own clause, so the two cannot disagree.
 */
export const countLogs = <ThrowOnError extends boolean = false>(
  options?: Options<CountLogsData, ThrowOnError>,
): RequestResult<CountLogsResponses, CountLogsErrors, ThrowOnError> =>
  (options?.client ?? client).get<CountLogsResponses, CountLogsErrors, ThrowOnError>({
    url: '/api/v1/logs/count',
    ...options,
  });

/**
 * List Campaigns
 */
export const listNeuroshillingCampaigns = <ThrowOnError extends boolean = false>(
  options?: Options<ListNeuroshillingCampaignsData, ThrowOnError>,
): RequestResult<
  ListNeuroshillingCampaignsResponses,
  ListNeuroshillingCampaignsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListNeuroshillingCampaignsResponses,
    ListNeuroshillingCampaignsErrors,
    ThrowOnError
  >({ url: '/api/v1/neuroshilling/campaigns', ...options });

/**
 * Create Campaign
 */
export const createNeuroshillingCampaign = <ThrowOnError extends boolean = false>(
  options: Options<CreateNeuroshillingCampaignData, ThrowOnError>,
): RequestResult<
  CreateNeuroshillingCampaignResponses,
  CreateNeuroshillingCampaignErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateNeuroshillingCampaignResponses,
    CreateNeuroshillingCampaignErrors,
    ThrowOnError
  >({
    url: '/api/v1/neuroshilling/campaigns',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Campaign
 *
 * Delete a campaign and everything hanging off it. A live run refuses (409).
 */
export const deleteNeuroshillingCampaign = <ThrowOnError extends boolean = false>(
  options: Options<DeleteNeuroshillingCampaignData, ThrowOnError>,
): RequestResult<
  DeleteNeuroshillingCampaignResponses,
  DeleteNeuroshillingCampaignErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteNeuroshillingCampaignResponses,
    DeleteNeuroshillingCampaignErrors,
    ThrowOnError
  >({ url: '/api/v1/neuroshilling/campaigns/{campaign_id}', ...options });

/**
 * Update Campaign
 *
 * Save the whole edited form: settings, targets and the account roster.
 */
export const updateNeuroshillingCampaign = <ThrowOnError extends boolean = false>(
  options: Options<UpdateNeuroshillingCampaignData, ThrowOnError>,
): RequestResult<
  UpdateNeuroshillingCampaignResponses,
  UpdateNeuroshillingCampaignErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateNeuroshillingCampaignResponses,
    UpdateNeuroshillingCampaignErrors,
    ThrowOnError
  >({
    url: '/api/v1/neuroshilling/campaigns/{campaign_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Board
 *
 * The whole page in one read: campaign, account pool, targets, run status.
 *
 * The roster is not a list of its own: ``available`` carries every offerable account
 * with the rostered ones flagged ``assigned``, for the reason
 * :class:`schemas.neuroshilling.NeuroshillingBoard` gives.
 */
export const getNeuroshillingBoard = <ThrowOnError extends boolean = false>(
  options: Options<GetNeuroshillingBoardData, ThrowOnError>,
): RequestResult<GetNeuroshillingBoardResponses, GetNeuroshillingBoardErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetNeuroshillingBoardResponses,
    GetNeuroshillingBoardErrors,
    ThrowOnError
  >({ url: '/api/v1/neuroshilling/campaigns/{campaign_id}/board', ...options });

/**
 * Get Scenario
 *
 * Roles, steps and the approval status — a read of its own, not a board field.
 *
 * Separate so the SPA can keep it OUT of the log-stream invalidation set: the
 * stream fires on every log line, and a scenario form refetched under the
 * operator's typing would lose what they were writing.
 */
export const getNeuroshillingScenario = <ThrowOnError extends boolean = false>(
  options: Options<GetNeuroshillingScenarioData, ThrowOnError>,
): RequestResult<GetNeuroshillingScenarioResponses, GetNeuroshillingScenarioErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetNeuroshillingScenarioResponses,
    GetNeuroshillingScenarioErrors,
    ThrowOnError
  >({ url: '/api/v1/neuroshilling/campaigns/{campaign_id}/scenario', ...options });

/**
 * Set Scenario
 *
 * Save the whole dialogue. ALWAYS returns the campaign to ``draft``.
 */
export const setNeuroshillingScenario = <ThrowOnError extends boolean = false>(
  options: Options<SetNeuroshillingScenarioData, ThrowOnError>,
): RequestResult<SetNeuroshillingScenarioResponses, SetNeuroshillingScenarioErrors, ThrowOnError> =>
  (options.client ?? client).put<
    SetNeuroshillingScenarioResponses,
    SetNeuroshillingScenarioErrors,
    ThrowOnError
  >({
    url: '/api/v1/neuroshilling/campaigns/{campaign_id}/scenario',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Generate Scenario
 *
 * Write a fresh dialogue with the LLM, replacing whatever the campaign had.
 *
 * 409 is a second click (``generation_in_progress``) or the rolling daily budget
 * (``llm_daily_limit_reached``); 503 is the provider having produced nothing
 * usable within its retry budget, or no key being configured at all.
 */
export const generateNeuroshillingScenario = <ThrowOnError extends boolean = false>(
  options: Options<GenerateNeuroshillingScenarioData, ThrowOnError>,
): RequestResult<
  GenerateNeuroshillingScenarioResponses,
  GenerateNeuroshillingScenarioErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    GenerateNeuroshillingScenarioResponses,
    GenerateNeuroshillingScenarioErrors,
    ThrowOnError
  >({
    url: '/api/v1/neuroshilling/campaigns/{campaign_id}/generate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Approve Scenario
 *
 * The ONLY way ``scenario_status`` becomes ``approved``, and it validates first.
 *
 * 503 is the media check itself failing to happen — Telegram rate-limited the read
 * or the socket died. Not 400: nothing about the scenario was found wanting, and
 * answering "some accounts cannot see the media" would send the operator to edit a
 * link that is fine.
 */
export const approveNeuroshillingScenario = <ThrowOnError extends boolean = false>(
  options: Options<ApproveNeuroshillingScenarioData, ThrowOnError>,
): RequestResult<
  ApproveNeuroshillingScenarioResponses,
  ApproveNeuroshillingScenarioErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ApproveNeuroshillingScenarioResponses,
    ApproveNeuroshillingScenarioErrors,
    ThrowOnError
  >({ url: '/api/v1/neuroshilling/campaigns/{campaign_id}/approve', ...options });

/**
 * Start Campaign
 *
 * Begin playing the approved dialogue into the campaign's targets.
 *
 * 409 covers every reason a run cannot begin: the scenario is still a draft, the
 * roster is short or leaves a role unstaffed, there are no targets, an account is
 * held by another feature, the campaign is already running, or ``run_mode`` is
 * ``parallel`` — which this build refuses on the server rather than merely hiding,
 * because the generated client types the field.
 */
export const startNeuroshillingCampaign = <ThrowOnError extends boolean = false>(
  options: Options<StartNeuroshillingCampaignData, ThrowOnError>,
): RequestResult<
  StartNeuroshillingCampaignResponses,
  StartNeuroshillingCampaignErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    StartNeuroshillingCampaignResponses,
    StartNeuroshillingCampaignErrors,
    ThrowOnError
  >({ url: '/api/v1/neuroshilling/campaigns/{campaign_id}/start', ...options });

/**
 * Stop Campaign
 *
 * Fence the run, cancel it, and answer with where it ended up.
 *
 * Idempotent: stopping a campaign that is already idle answers its current status
 * rather than a conflict. By the time a click lands the run may have finished a
 * second ago, and "conflict" is noise rather than information about that.
 */
export const stopNeuroshillingCampaign = <ThrowOnError extends boolean = false>(
  options: Options<StopNeuroshillingCampaignData, ThrowOnError>,
): RequestResult<
  StopNeuroshillingCampaignResponses,
  StopNeuroshillingCampaignErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    StopNeuroshillingCampaignResponses,
    StopNeuroshillingCampaignErrors,
    ThrowOnError
  >({ url: '/api/v1/neuroshilling/campaigns/{campaign_id}/stop', ...options });
