// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  AddWarmingChannelsData,
  AddWarmingChannelsErrors,
  AddWarmingChannelsResponses,
  AssignCampaignAccountData,
  AssignCampaignAccountErrors,
  AssignCampaignAccountResponses,
  CheckAccountData,
  CheckAccountErrors,
  CheckAccountResponses,
  CreateCampaignData,
  CreateCampaignErrors,
  CreateCampaignResponses,
  DeleteAccountData,
  DeleteAccountErrors,
  DeleteAccountResponses,
  GetHealthData,
  GetHealthResponses,
  GetMeData,
  GetMeErrors,
  GetMeResponses,
  GetNeurocommentBoardData,
  GetNeurocommentBoardErrors,
  GetNeurocommentBoardResponses,
  GetNeurocommentRuntimeData,
  GetNeurocommentRuntimeErrors,
  GetNeurocommentRuntimeResponses,
  GetWarmingBoardData,
  GetWarmingBoardErrors,
  GetWarmingBoardResponses,
  GetWarmingSettingsData,
  GetWarmingSettingsErrors,
  GetWarmingSettingsResponses,
  ImportAccountTdataData,
  ImportAccountTdataErrors,
  ImportAccountTdataResponses,
  LinkCampaignChannelData,
  LinkCampaignChannelErrors,
  LinkCampaignChannelResponses,
  ListAccountsData,
  ListAccountsErrors,
  ListAccountsResponses,
  ListCampaignsData,
  ListCampaignsErrors,
  ListCampaignsResponses,
  ListWarmingChannelsData,
  ListWarmingChannelsErrors,
  ListWarmingChannelsResponses,
  LoginData,
  LoginErrors,
  LoginResponses,
  LogoutData,
  LogoutResponses,
  RemoveWarmingChannelData,
  RemoveWarmingChannelErrors,
  RemoveWarmingChannelResponses,
  SetAccountPhotoData,
  SetAccountPhotoErrors,
  SetAccountPhotoResponses,
  StartNeurocommentData,
  StartNeurocommentErrors,
  StartNeurocommentResponses,
  StartWarmingData,
  StartWarmingErrors,
  StartWarmingResponses,
  StopNeurocommentData,
  StopNeurocommentErrors,
  StopNeurocommentResponses,
  StopWarmingData,
  StopWarmingErrors,
  StopWarmingResponses,
  UpdateAccountProfileData,
  UpdateAccountProfileErrors,
  UpdateAccountProfileResponses,
  UpdateWarmingSettingsData,
  UpdateWarmingSettingsErrors,
  UpdateWarmingSettingsResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Login
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Logout
 */
export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>,
) =>
  (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
    url: '/api/v1/auth/logout',
    ...options,
  });

/**
 * Me
 */
export const getMe = <ThrowOnError extends boolean = false>(
  options?: Options<GetMeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({
    url: '/api/v1/auth/me',
    ...options,
  });

/**
 * Health
 */
export const getHealth = <ThrowOnError extends boolean = false>(
  options?: Options<GetHealthData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({
    url: '/api/v1/health',
    ...options,
  });

/**
 * List Accounts
 */
export const listAccounts = <ThrowOnError extends boolean = false>(
  options?: Options<ListAccountsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListAccountsResponses, ListAccountsErrors, ThrowOnError>({
    url: '/api/v1/accounts',
    ...options,
  });

/**
 * Check Account
 */
export const checkAccount = <ThrowOnError extends boolean = false>(
  options: Options<CheckAccountData, ThrowOnError>,
) =>
  (options.client ?? client).post<CheckAccountResponses, CheckAccountErrors, ThrowOnError>({
    url: '/api/v1/accounts/check',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update Account Profile
 */
export const updateAccountProfile = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAccountProfileData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    UpdateAccountProfileResponses,
    UpdateAccountProfileErrors,
    ThrowOnError
  >({
    url: '/api/v1/accounts/profile',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Account
 */
export const deleteAccount = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAccountData, ThrowOnError>,
) =>
  (options.client ?? client).delete<DeleteAccountResponses, DeleteAccountErrors, ThrowOnError>({
    url: '/api/v1/accounts/{account_id}',
    ...options,
  });

/**
 * Import Account Tdata
 */
export const importAccountTdata = <ThrowOnError extends boolean = false>(
  options: Options<ImportAccountTdataData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ImportAccountTdataResponses,
    ImportAccountTdataErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: '/api/v1/accounts/import-tdata',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Set Account Photo
 */
export const setAccountPhoto = <ThrowOnError extends boolean = false>(
  options: Options<SetAccountPhotoData, ThrowOnError>,
) =>
  (options.client ?? client).post<SetAccountPhotoResponses, SetAccountPhotoErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/accounts/photo',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Get Warming Board
 */
export const getWarmingBoard = <ThrowOnError extends boolean = false>(
  options?: Options<GetWarmingBoardData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetWarmingBoardResponses, GetWarmingBoardErrors, ThrowOnError>({
    url: '/api/v1/warming/board',
    ...options,
  });

/**
 * Start Warming
 */
export const startWarming = <ThrowOnError extends boolean = false>(
  options: Options<StartWarmingData, ThrowOnError>,
) =>
  (options.client ?? client).post<StartWarmingResponses, StartWarmingErrors, ThrowOnError>({
    url: '/api/v1/warming/start',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Stop Warming
 */
export const stopWarming = <ThrowOnError extends boolean = false>(
  options: Options<StopWarmingData, ThrowOnError>,
) =>
  (options.client ?? client).post<StopWarmingResponses, StopWarmingErrors, ThrowOnError>({
    url: '/api/v1/warming/stop',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Warming Channels
 */
export const listWarmingChannels = <ThrowOnError extends boolean = false>(
  options?: Options<ListWarmingChannelsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListWarmingChannelsResponses,
    ListWarmingChannelsErrors,
    ThrowOnError
  >({ url: '/api/v1/warming/channels', ...options });

/**
 * Add Warming Channels
 */
export const addWarmingChannels = <ThrowOnError extends boolean = false>(
  options: Options<AddWarmingChannelsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AddWarmingChannelsResponses,
    AddWarmingChannelsErrors,
    ThrowOnError
  >({
    url: '/api/v1/warming/channels',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove Warming Channel
 */
export const removeWarmingChannel = <ThrowOnError extends boolean = false>(
  options: Options<RemoveWarmingChannelData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RemoveWarmingChannelResponses,
    RemoveWarmingChannelErrors,
    ThrowOnError
  >({
    url: '/api/v1/warming/channels/remove',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Warming Settings
 */
export const getWarmingSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetWarmingSettingsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetWarmingSettingsResponses,
    GetWarmingSettingsErrors,
    ThrowOnError
  >({ url: '/api/v1/warming/settings', ...options });

/**
 * Update Warming Settings
 */
export const updateWarmingSettings = <ThrowOnError extends boolean = false>(
  options: Options<UpdateWarmingSettingsData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateWarmingSettingsResponses,
    UpdateWarmingSettingsErrors,
    ThrowOnError
  >({
    url: '/api/v1/warming/settings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Campaigns
 */
export const listCampaigns = <ThrowOnError extends boolean = false>(
  options?: Options<ListCampaignsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListCampaignsResponses, ListCampaignsErrors, ThrowOnError>({
    url: '/api/v1/neurocomment/campaigns',
    ...options,
  });

/**
 * Create Campaign
 */
export const createCampaign = <ThrowOnError extends boolean = false>(
  options: Options<CreateCampaignData, ThrowOnError>,
) =>
  (options.client ?? client).post<CreateCampaignResponses, CreateCampaignErrors, ThrowOnError>({
    url: '/api/v1/neurocomment/campaigns',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Board
 */
export const getNeurocommentBoard = <ThrowOnError extends boolean = false>(
  options: Options<GetNeurocommentBoardData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetNeurocommentBoardResponses,
    GetNeurocommentBoardErrors,
    ThrowOnError
  >({ url: '/api/v1/neurocomment/campaigns/{campaign_id}/board', ...options });

/**
 * Link Channel
 */
export const linkCampaignChannel = <ThrowOnError extends boolean = false>(
  options: Options<LinkCampaignChannelData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    LinkCampaignChannelResponses,
    LinkCampaignChannelErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/campaigns/{campaign_id}/channels',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Assign Account
 */
export const assignCampaignAccount = <ThrowOnError extends boolean = false>(
  options: Options<AssignCampaignAccountData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AssignCampaignAccountResponses,
    AssignCampaignAccountErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/campaigns/{campaign_id}/accounts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Runtime
 */
export const getNeurocommentRuntime = <ThrowOnError extends boolean = false>(
  options?: Options<GetNeurocommentRuntimeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetNeurocommentRuntimeResponses,
    GetNeurocommentRuntimeErrors,
    ThrowOnError
  >({ url: '/api/v1/neurocomment/runtime', ...options });

/**
 * Start
 */
export const startNeurocomment = <ThrowOnError extends boolean = false>(
  options: Options<StartNeurocommentData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    StartNeurocommentResponses,
    StartNeurocommentErrors,
    ThrowOnError
  >({
    url: '/api/v1/neurocomment/start',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Stop
 */
export const stopNeurocomment = <ThrowOnError extends boolean = false>(
  options?: Options<StopNeurocommentData, ThrowOnError>,
) =>
  (options?.client ?? client).post<StopNeurocommentResponses, StopNeurocommentErrors, ThrowOnError>(
    { url: '/api/v1/neurocomment/stop', ...options },
  );
