// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccountCheckRequest
 */
export type AccountCheckRequest = {
  /**
   * Account Id
   */
  account_id: string;
};

/**
 * AccountProfileUpdateRequest
 */
export type AccountProfileUpdateRequest = {
  /**
   * Account Id
   */
  account_id: string;
  /**
   * First Name
   */
  first_name: string;
  /**
   * Last Name
   */
  last_name?: string | null;
  /**
   * Username
   */
  username?: string | null;
  /**
   * Bio
   */
  bio?: string | null;
};

/**
 * AccountRead
 */
export type AccountRead = {
  /**
   * Account Id
   */
  account_id: string;
  /**
   * Label
   */
  label?: string | null;
  /**
   * Session Name
   */
  session_name?: string | null;
  /**
   * Status
   */
  status:
    | 'new'
    | 'alive'
    | 'unauthorized'
    | 'session_error'
    | 'account_error'
    | 'flood_wait'
    | 'network_error'
    | 'proxy_error'
    | 'unknown_error';
  /**
   * User Id
   */
  user_id?: number | null;
  /**
   * Phone
   */
  phone?: string | null;
  /**
   * Username
   */
  username?: string | null;
  /**
   * First Name
   */
  first_name?: string | null;
  /**
   * Last Name
   */
  last_name?: string | null;
  /**
   * Last Checked At
   */
  last_checked_at?: string | null;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Device Platform
   */
  device_platform?: string | null;
  /**
   * Device Model
   */
  device_model?: string | null;
  /**
   * Device System Version
   */
  device_system_version?: string | null;
  /**
   * Device App Version
   */
  device_app_version?: string | null;
  /**
   * Bio
   */
  bio?: string | null;
  /**
   * Proxy Type
   */
  proxy_type?: string | null;
  /**
   * Proxy Host
   */
  proxy_host?: string | null;
  /**
   * Proxy Port
   */
  proxy_port?: number | null;
  /**
   * Proxy Status
   */
  proxy_status?: string | null;
  /**
   * Proxy Last Checked At
   */
  proxy_last_checked_at?: string | null;
  /**
   * Proxy Last Error
   */
  proxy_last_error?: string | null;
  /**
   * Proxy Exit Ip
   */
  proxy_exit_ip?: string | null;
  /**
   * Proxy Country Code
   */
  proxy_country_code?: string | null;
  /**
   * Proxy Country Name
   */
  proxy_country_name?: string | null;
};

/**
 * ActionResult
 *
 * Outcome of one ``execute`` call.
 */
export type ActionResult = {
  /**
   * Status
   */
  status: 'ok' | 'flood_wait' | 'slow_mode_wait' | 'premium_wait' | 'peer_flood' | 'failed';
  /**
   * Action Type
   */
  action_type: string;
  /**
   * Account Id
   */
  account_id: string;
  /**
   * Message Id
   */
  message_id?: number | null;
  /**
   * Flood Wait Seconds
   */
  flood_wait_seconds?: number | null;
  /**
   * Error Type
   */
  error_type?: string | null;
  /**
   * Error Message
   */
  error_message?: string | null;
};

/**
 * Body_importAccountTdata
 */
export type BodyImportAccountTdata = {
  /**
   * File
   */
  file: Blob | File;
  /**
   * Label
   */
  label?: string | null;
};

/**
 * Body_setAccountPhoto
 */
export type BodySetAccountPhoto = {
  /**
   * Account Id
   */
  account_id: string;
  /**
   * File
   */
  file: Blob | File;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HealthStatus
 */
export type HealthStatus = {
  /**
   * Status
   */
  status?: 'ok';
};

/**
 * Page[AccountRead]
 */
export type PageAccountRead = {
  /**
   * Items
   */
  items: Array<AccountRead>;
  /**
   * Next Cursor
   */
  next_cursor?: string | null;
};

/**
 * TdataImportResult
 *
 * Outcome of one :func:`services.accounts.sessions.import_account_tdata` call.
 *
 * Wrapping the imported accounts in a model (instead of returning a raw
 * ``list[AccountRead]``) keeps the service boundary Pydantic-only, leaves room
 * to add per-import metadata (counts, partial-failure summaries) without
 * breaking every call site, and matches the convention used by ``list_accounts``
 * and other multi-row reads.
 */
export type TdataImportResult = {
  /**
   * Accounts
   */
  accounts?: Array<AccountRead>;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/health';
};

export type GetHealthResponses = {
  /**
   * Successful Response
   */
  200: HealthStatus;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type ListAccountsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Query
     */
    query?: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Cursor
     */
    cursor?: string | null;
    /**
     * Limit
     */
    limit?: number;
  };
  url: '/api/v1/accounts';
};

export type ListAccountsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListAccountsError = ListAccountsErrors[keyof ListAccountsErrors];

export type ListAccountsResponses = {
  /**
   * Successful Response
   */
  200: PageAccountRead;
};

export type ListAccountsResponse = ListAccountsResponses[keyof ListAccountsResponses];

export type CheckAccountData = {
  body: AccountCheckRequest;
  path?: never;
  query?: never;
  url: '/api/v1/accounts/check';
};

export type CheckAccountErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CheckAccountError = CheckAccountErrors[keyof CheckAccountErrors];

export type CheckAccountResponses = {
  /**
   * Successful Response
   */
  200: AccountRead;
};

export type CheckAccountResponse = CheckAccountResponses[keyof CheckAccountResponses];

export type UpdateAccountProfileData = {
  body: AccountProfileUpdateRequest;
  path?: never;
  query?: never;
  url: '/api/v1/accounts/profile';
};

export type UpdateAccountProfileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateAccountProfileError =
  UpdateAccountProfileErrors[keyof UpdateAccountProfileErrors];

export type UpdateAccountProfileResponses = {
  /**
   * Successful Response
   */
  200: AccountRead;
};

export type UpdateAccountProfileResponse =
  UpdateAccountProfileResponses[keyof UpdateAccountProfileResponses];

export type DeleteAccountData = {
  body?: never;
  path: {
    /**
     * Account Id
     */
    account_id: string;
  };
  query?: never;
  url: '/api/v1/accounts/{account_id}';
};

export type DeleteAccountErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type ImportAccountTdataData = {
  body: BodyImportAccountTdata;
  path?: never;
  query?: never;
  url: '/api/v1/accounts/import-tdata';
};

export type ImportAccountTdataErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ImportAccountTdataError = ImportAccountTdataErrors[keyof ImportAccountTdataErrors];

export type ImportAccountTdataResponses = {
  /**
   * Successful Response
   */
  200: TdataImportResult;
};

export type ImportAccountTdataResponse =
  ImportAccountTdataResponses[keyof ImportAccountTdataResponses];

export type SetAccountPhotoData = {
  body: BodySetAccountPhoto;
  path?: never;
  query?: never;
  url: '/api/v1/accounts/photo';
};

export type SetAccountPhotoErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SetAccountPhotoError = SetAccountPhotoErrors[keyof SetAccountPhotoErrors];

export type SetAccountPhotoResponses = {
  /**
   * Successful Response
   */
  200: ActionResult;
};

export type SetAccountPhotoResponse = SetAccountPhotoResponses[keyof SetAccountPhotoResponses];
