// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccountRead
 */
export type AccountRead = {
  /**
   * Account Id
   */
  account_id: string;
  /**
   * Label
   */
  label?: string | null;
  /**
   * Session Name
   */
  session_name?: string | null;
  /**
   * Status
   */
  status:
    | "new"
    | "alive"
    | "unauthorized"
    | "session_error"
    | "account_error"
    | "flood_wait"
    | "network_error"
    | "proxy_error"
    | "unknown_error";
  /**
   * User Id
   */
  user_id?: number | null;
  /**
   * Phone
   */
  phone?: string | null;
  /**
   * Username
   */
  username?: string | null;
  /**
   * First Name
   */
  first_name?: string | null;
  /**
   * Last Name
   */
  last_name?: string | null;
  /**
   * Last Checked At
   */
  last_checked_at?: string | null;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Device Platform
   */
  device_platform?: string | null;
  /**
   * Device Model
   */
  device_model?: string | null;
  /**
   * Device System Version
   */
  device_system_version?: string | null;
  /**
   * Device App Version
   */
  device_app_version?: string | null;
  /**
   * Bio
   */
  bio?: string | null;
  /**
   * Proxy Type
   */
  proxy_type?: string | null;
  /**
   * Proxy Host
   */
  proxy_host?: string | null;
  /**
   * Proxy Port
   */
  proxy_port?: number | null;
  /**
   * Proxy Status
   */
  proxy_status?: string | null;
  /**
   * Proxy Last Checked At
   */
  proxy_last_checked_at?: string | null;
  /**
   * Proxy Last Error
   */
  proxy_last_error?: string | null;
  /**
   * Proxy Exit Ip
   */
  proxy_exit_ip?: string | null;
  /**
   * Proxy Country Code
   */
  proxy_country_code?: string | null;
  /**
   * Proxy Country Name
   */
  proxy_country_name?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HealthStatus
 */
export type HealthStatus = {
  /**
   * Status
   */
  status?: "ok";
};

/**
 * Page[AccountRead]
 */
export type PageAccountRead = {
  /**
   * Items
   */
  items: Array<AccountRead>;
  /**
   * Next Cursor
   */
  next_cursor?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/health";
};

export type GetHealthResponses = {
  /**
   * Successful Response
   */
  200: HealthStatus;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type ListAccountsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Query
     */
    query?: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Cursor
     */
    cursor?: string | null;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/accounts";
};

export type ListAccountsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListAccountsError = ListAccountsErrors[keyof ListAccountsErrors];

export type ListAccountsResponses = {
  /**
   * Successful Response
   */
  200: PageAccountRead;
};

export type ListAccountsResponse =
  ListAccountsResponses[keyof ListAccountsResponses];
