// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccountChannelOnboarding
 *
 * Outcome of preparing one account to comment on one channel.
 *
 * ``reason`` carries a short human note for the non-``ready`` states (the
 * flood-wait detail, the failing error type, etc.).
 */
export type AccountChannelOnboarding = {
  /**
   * Account Id
   */
  account_id: string;
  /**
   * Channel
   */
  channel: string;
  /**
   * State
   */
  state:
    | 'ready'
    | 'comments_off'
    | 'join_by_request'
    | 'chat_restricted'
    | 'bot_challenge'
    | 'bot_challenge_backoff'
    | 'joining'
    | 'failed';
  /**
   * Reason
   */
  reason?: string | null;
};

/**
 * AccountChannelReadiness
 *
 * One channel's readiness summary on an account card.
 */
export type AccountChannelReadiness = {
  /**
   * Channel
   */
  channel: string;
  /**
   * Ready
   */
  ready: boolean;
  /**
   * Joined
   */
  joined: boolean;
  /**
   * Captcha Passed
   */
  captcha_passed: boolean;
  /**
   * Human Skipped
   */
  human_skipped?: boolean;
};

/**
 * AccountCheckRequest
 */
export type AccountCheckRequest = {
  /**
   * Account Id
   */
  account_id: string;
};

/**
 * AccountProfileUpdateRequest
 */
export type AccountProfileUpdateRequest = {
  /**
   * Account Id
   */
  account_id: string;
  /**
   * First Name
   */
  first_name: string;
  /**
   * Last Name
   */
  last_name?: string | null;
  /**
   * Username
   */
  username?: string | null;
  /**
   * Bio
   */
  bio?: string | null;
};

/**
 * AccountProfileView
 *
 * JSON-safe live profile for the edit-profile modal.
 */
export type AccountProfileView = {
  /**
   * Error
   */
  error?: string | null;
  /**
   * Avatar Data Uri
   */
  avatar_data_uri?: string | null;
  /**
   * Photos
   */
  photos?: Array<ProfilePhotoView>;
  /**
   * Stories
   */
  stories?: Array<ProfileStoryView>;
  /**
   * Music
   */
  music?: Array<ProfileMusicView>;
  /**
   * Music Supported
   */
  music_supported?: boolean;
};

/**
 * AccountRead
 */
export type AccountRead = {
  /**
   * Account Id
   */
  account_id: string;
  /**
   * Label
   */
  label?: string | null;
  /**
   * Session Name
   */
  session_name?: string | null;
  /**
   * Status
   */
  status:
    | 'new'
    | 'alive'
    | 'unauthorized'
    | 'session_error'
    | 'account_error'
    | 'flood_wait'
    | 'network_error'
    | 'proxy_error'
    | 'unknown_error';
  /**
   * User Id
   */
  user_id?: number | null;
  /**
   * Phone
   */
  phone?: string | null;
  /**
   * Username
   */
  username?: string | null;
  /**
   * First Name
   */
  first_name?: string | null;
  /**
   * Last Name
   */
  last_name?: string | null;
  /**
   * Last Checked At
   */
  last_checked_at?: string | null;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Device Platform
   */
  device_platform?: string | null;
  /**
   * Device Model
   */
  device_model?: string | null;
  /**
   * Device System Version
   */
  device_system_version?: string | null;
  /**
   * Device App Version
   */
  device_app_version?: string | null;
  /**
   * Device Lang
   */
  device_lang?: string | null;
  /**
   * Bio
   */
  bio?: string | null;
  /**
   * Proxy Id
   */
  proxy_id?: string | null;
  /**
   * Proxy Type
   */
  proxy_type?: string | null;
  /**
   * Proxy Host
   */
  proxy_host?: string | null;
  /**
   * Proxy Port
   */
  proxy_port?: number | null;
  /**
   * Proxy Status
   */
  proxy_status?: string | null;
  /**
   * Proxy Last Checked At
   */
  proxy_last_checked_at?: string | null;
  /**
   * Proxy Last Error
   */
  proxy_last_error?: string | null;
  /**
   * Proxy Exit Ip
   */
  proxy_exit_ip?: string | null;
  /**
   * Proxy Country Code
   */
  proxy_country_code?: string | null;
  /**
   * Proxy Country Name
   */
  proxy_country_name?: string | null;
  /**
   * Trust Score
   */
  trust_score?: number | null;
  /**
   * Trust Band
   */
  trust_band?: 'excellent' | 'good' | 'watch' | 'at_risk' | 'critical' | null;
  /**
   * Spam Status
   */
  spam_status?: 'clean' | 'limited' | 'unknown' | null;
  /**
   * Spam Detail
   */
  spam_detail?: string | null;
};

/**
 * ActionResult
 *
 * Outcome of one ``execute`` call.
 */
export type ActionResult = {
  /**
   * Status
   */
  status: 'ok' | 'flood_wait' | 'slow_mode_wait' | 'premium_wait' | 'peer_flood' | 'failed';
  /**
   * Action Type
   */
  action_type: string;
  /**
   * Account Id
   */
  account_id: string;
  /**
   * Message Id
   */
  message_id?: number | null;
  /**
   * Flood Wait Seconds
   */
  flood_wait_seconds?: number | null;
  /**
   * Error Type
   */
  error_type?: string | null;
  /**
   * Error Message
   */
  error_message?: string | null;
};

/**
 * AddChannelsRequest
 *
 * Raw user input — one or many links/usernames, newline- or comma-separated.
 */
export type AddChannelsRequest = {
  /**
   * Raw
   */
  raw: string;
};

/**
 * AssignAccountRequest
 *
 * Assign an account to a campaign (the campaign id is the route path param).
 */
export type AssignAccountRequest = {
  /**
   * Account Id
   */
  account_id: string;
};

/**
 * Body_addAccountMusic
 */
export type BodyAddAccountMusic = {
  /**
   * File
   */
  file: Blob | File;
  /**
   * Title
   */
  title?: string | null;
  /**
   * Performer
   */
  performer?: string | null;
};

/**
 * Body_importAccountSession
 */
export type BodyImportAccountSession = {
  /**
   * File
   */
  file: Blob | File;
  /**
   * Label
   */
  label?: string | null;
};

/**
 * Body_importAccountTdata
 */
export type BodyImportAccountTdata = {
  /**
   * File
   */
  file: Blob | File;
  /**
   * Label
   */
  label?: string | null;
};

/**
 * Body_postAccountStory
 */
export type BodyPostAccountStory = {
  /**
   * File
   */
  file: Blob | File;
  /**
   * Media Kind
   */
  media_kind?: 'image' | 'video';
  /**
   * Caption
   */
  caption?: string | null;
  /**
   * Privacy Preset
   */
  privacy_preset?: 'contacts' | 'close_friends' | 'public';
  /**
   * Protect Content
   */
  protect_content?: boolean;
};

/**
 * Body_setAccountPhoto
 */
export type BodySetAccountPhoto = {
  /**
   * Account Id
   */
  account_id: string;
  /**
   * File
   */
  file: Blob | File;
};

/**
 * CampaignCreate
 *
 * User input to open a campaign — the product mention lives in the prompt.
 */
export type CampaignCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Prompt
   */
  prompt: string;
  /**
   * Status
   */
  status?: 'active' | 'paused' | 'archived';
};

/**
 * CampaignList
 *
 * Wrapper so callers never receive a raw list (non-negotiable #2).
 */
export type CampaignList = {
  /**
   * Campaigns
   */
  campaigns?: Array<NeurocommentCampaign>;
};

/**
 * ChallengeRow
 *
 * One persisted challenge audit row, as the operator drill-down reads it.
 */
export type ChallengeRow = {
  /**
   * Account Id
   */
  account_id: string;
  /**
   * Channel
   */
  channel: string;
  /**
   * Raw Text
   */
  raw_text: string;
  /**
   * Button Labels
   */
  button_labels?: Array<string>;
  /**
   * Outcome
   */
  outcome: string;
  /**
   * Decided At
   */
  decided_at: string;
  /**
   * Reasoning
   */
  reasoning?: string | null;
};

/**
 * ChallengeRowList
 *
 * Wrapper so the repo returns a model, never a raw list (non-negotiable #2).
 */
export type ChallengeRowList = {
  /**
   * Rows
   */
  rows?: Array<ChallengeRow>;
};

/**
 * ChannelLinkOutcome
 *
 * Result of attaching a channel to a campaign.
 *
 * ``already_assigned`` means the channel is the active target of another campaign
 * (the repository's uniqueness guard). The service returns this instead of letting
 * ``ChannelAlreadyAssignedError`` reach the UI, so features never catch internals (#2).
 */
export type ChannelLinkOutcome = {
  /**
   * Status
   */
  status: 'linked' | 'already_assigned';
  /**
   * Channel
   */
  channel: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HealthStatus
 */
export type HealthStatus = {
  /**
   * Status
   */
  status?: 'ok';
};

/**
 * LinkChannelRequest
 *
 * Attach a channel to a campaign (the campaign id is the route path param).
 */
export type LinkChannelRequest = {
  /**
   * Channel
   */
  channel: string;
};

/**
 * LogEntry
 *
 * One row of the ``logs`` SQLite table.
 */
export type LogEntry = {
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Level
   */
  level: 'INFO' | 'WARNING' | 'ERROR';
  /**
   * Status
   */
  status: 'success' | 'warning' | 'error';
  /**
   * Account Id
   */
  account_id: string | null;
  /**
   * Event
   */
  event: string;
  /**
   * Extra
   */
  extra?: {
    [key: string]: unknown;
  };
};

/**
 * LoginRequest
 */
export type LoginRequest = {
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
};

/**
 * MusicRemoveRequest
 */
export type MusicRemoveRequest = {
  /**
   * File Id
   */
  file_id: number;
  /**
   * Access Hash
   */
  access_hash: number;
  /**
   * File Reference
   */
  file_reference: string;
};

/**
 * NeurocommentAccountCard
 *
 * Per-account card in the work view: limits, health, last activity.
 */
export type NeurocommentAccountCard = {
  /**
   * Account Id
   */
  account_id: string;
  /**
   * Label
   */
  label: string;
  /**
   * Health
   */
  health: string;
  /**
   * Trust Score
   */
  trust_score: number;
  /**
   * Trust Band
   */
  trust_band: string;
  /**
   * Spam Status
   */
  spam_status?: string | null;
  /**
   * Comments Last Hour
   */
  comments_last_hour: number;
  /**
   * Max Comments Per Hour
   */
  max_comments_per_hour: number;
  /**
   * Comments Today
   */
  comments_today: number;
  /**
   * Last Comment At
   */
  last_comment_at?: string | null;
  /**
   * Last Comment Text
   */
  last_comment_text?: string | null;
  /**
   * Readiness
   */
  readiness?: Array<AccountChannelReadiness>;
};

/**
 * NeurocommentBoard
 *
 * Bulk read model for the work view of one campaign.
 */
export type NeurocommentBoard = {
  /**
   * Campaign Id
   */
  campaign_id: string;
  /**
   * Campaign Name
   */
  campaign_name: string;
  /**
   * Status
   */
  status: 'active' | 'paused' | 'archived';
  /**
   * Solver Enabled
   */
  solver_enabled?: boolean | null;
  /**
   * Accounts
   */
  accounts?: Array<NeurocommentAccountCard>;
  /**
   * Channels
   */
  channels?: Array<NeurocommentChannelRow>;
};

/**
 * NeurocommentCampaign
 *
 * One row of ``neurocomment_campaigns``.
 */
export type NeurocommentCampaign = {
  /**
   * Campaign Id
   */
  campaign_id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Prompt
   */
  prompt: string;
  /**
   * Status
   */
  status: 'active' | 'paused' | 'archived';
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Solver Enabled
   */
  solver_enabled?: boolean | null;
};

/**
 * NeurocommentChannelRow
 *
 * Per-channel row: aggregate status derived from readiness + linked group.
 */
export type NeurocommentChannelRow = {
  /**
   * Channel
   */
  channel: string;
  /**
   * Status
   */
  status:
    | 'ready'
    | 'comments_off'
    | 'join_by_request'
    | 'chat_restricted'
    | 'bot_challenge'
    | 'bot_challenge_backoff'
    | 'throttled';
  /**
   * Ready Accounts
   */
  ready_accounts: number;
  /**
   * Total Accounts
   */
  total_accounts: number;
};

/**
 * NeurocommentRuntimeStatus
 *
 * Fleet-wide runtime state for the page's running indicator + live animation.
 *
 * ``running`` is the single source of truth the UI animates on: the engine is
 * one fleet listener (not per-campaign), so the persisted listener account id
 * being set means the engine is live. ``active_channels`` is the size of the
 * watch set across all active campaigns (what the listener actually watches).
 */
export type NeurocommentRuntimeStatus = {
  /**
   * Running
   */
  running: boolean;
  /**
   * Active Channels
   */
  active_channels?: number;
  /**
   * Listener Account Id
   */
  listener_account_id?: string | null;
};

/**
 * NeurocommentSettings
 *
 * Operator-editable neurocomment limits — the engine reads these at selection.
 */
export type NeurocommentSettings = {
  /**
   * Max Comments Per Hour
   */
  max_comments_per_hour: number;
  /**
   * Max Comments Per Channel Per Day
   */
  max_comments_per_channel_per_day: number;
  /**
   * Reply Delay Min Seconds
   */
  reply_delay_min_seconds: number;
  /**
   * Reply Delay Max Seconds
   */
  reply_delay_max_seconds: number;
  /**
   * Min Trust Score
   */
  min_trust_score: number;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * NeurocommentSettingsUpdate
 *
 * Caller-supplied neurocomment-settings change from the Settings screen.
 */
export type NeurocommentSettingsUpdate = {
  /**
   * Max Comments Per Hour
   */
  max_comments_per_hour: number;
  /**
   * Max Comments Per Channel Per Day
   */
  max_comments_per_channel_per_day: number;
  /**
   * Reply Delay Min Seconds
   */
  reply_delay_min_seconds: number;
  /**
   * Reply Delay Max Seconds
   */
  reply_delay_max_seconds: number;
  /**
   * Min Trust Score
   */
  min_trust_score: number;
};

/**
 * Page[AccountRead]
 */
export type PageAccountRead = {
  /**
   * Items
   */
  items: Array<AccountRead>;
  /**
   * Next Cursor
   */
  next_cursor?: string | null;
};

/**
 * Page[LogEntry]
 */
export type PageLogEntry = {
  /**
   * Items
   */
  items: Array<LogEntry>;
  /**
   * Next Cursor
   */
  next_cursor?: string | null;
};

/**
 * PhoneCodeRequestResult
 *
 * API response after a code is sent — confirmation only, no secrets.
 */
export type PhoneCodeRequestResult = {
  /**
   * Account Id
   */
  account_id: string;
  /**
   * Phone
   */
  phone: string;
};

/**
 * PhotoRemoveRequest
 */
export type PhotoRemoveRequest = {
  /**
   * Photo Id
   */
  photo_id: number;
  /**
   * Access Hash
   */
  access_hash: number;
  /**
   * File Reference
   */
  file_reference: string;
};

/**
 * ProfileMusicView
 */
export type ProfileMusicView = {
  /**
   * File Id
   */
  file_id: number;
  /**
   * Title
   */
  title?: string | null;
  /**
   * Performer
   */
  performer?: string | null;
  /**
   * Access Hash
   */
  access_hash?: number;
  /**
   * File Reference
   */
  file_reference?: string;
};

/**
 * ProfilePhotoView
 */
export type ProfilePhotoView = {
  /**
   * Photo Id
   */
  photo_id: number;
  /**
   * Access Hash
   */
  access_hash: number;
  /**
   * File Reference
   */
  file_reference: string;
  /**
   * Thumb Data Uri
   */
  thumb_data_uri?: string | null;
};

/**
 * ProfileStoryView
 */
export type ProfileStoryView = {
  /**
   * Story Id
   */
  story_id: number;
  /**
   * Kind
   */
  kind?: string;
  /**
   * Caption
   */
  caption?: string | null;
  /**
   * Privacy Preset
   */
  privacy_preset?: string;
  /**
   * Is Pinned
   */
  is_pinned?: boolean;
  /**
   * Thumb Data Uri
   */
  thumb_data_uri?: string | null;
};

/**
 * PromoteRequest
 *
 * Body for promote/unpromote: graduate an account to/from the neurocomment pool.
 */
export type PromoteRequest = {
  /**
   * Account Id
   */
  account_id: string;
};

/**
 * ProxyAssignRequest
 */
export type ProxyAssignRequest = {
  /**
   * Account Id
   */
  account_id: string;
};

/**
 * ProxyCheckResult
 */
export type ProxyCheckResult = {
  /**
   * Status
   */
  status: 'unknown' | 'tcp_working' | 'failed';
  /**
   * Last Error
   */
  last_error?: string | null;
  /**
   * Exit Ip
   */
  exit_ip?: string | null;
  /**
   * Country Code
   */
  country_code?: string | null;
  /**
   * Country Name
   */
  country_name?: string | null;
  /**
   * Asn
   */
  asn?: string | null;
  /**
   * Is Datacenter
   */
  is_datacenter?: boolean;
};

/**
 * ProxyCreate
 *
 * Operator input when adding a proxy to the pool.
 */
export type ProxyCreate = {
  /**
   * Proxy Type
   */
  proxy_type: 'socks5' | 'https';
  /**
   * Host
   */
  host: string;
  /**
   * Port
   */
  port: number;
  /**
   * Username
   */
  username?: string | null;
  /**
   * Password
   */
  password?: string | null;
};

/**
 * ProxyList
 */
export type ProxyList = {
  /**
   * Proxies
   */
  proxies: Array<ProxyRead>;
};

/**
 * ProxyRead
 *
 * A pool proxy as shown on the Accounts page (masked credentials).
 */
export type ProxyRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Proxy Type
   */
  proxy_type: 'socks5' | 'https';
  /**
   * Host
   */
  host: string;
  /**
   * Port
   */
  port: number;
  /**
   * Username
   */
  username?: string | null;
  /**
   * Has Password
   */
  has_password: boolean;
  /**
   * Status
   */
  status: 'unknown' | 'tcp_working' | 'failed';
  /**
   * Last Checked At
   */
  last_checked_at?: string | null;
  /**
   * Last Error
   */
  last_error?: string | null;
  /**
   * Exit Ip
   */
  exit_ip?: string | null;
  /**
   * Country Code
   */
  country_code?: string | null;
  /**
   * Country Name
   */
  country_name?: string | null;
  /**
   * Asn
   */
  asn?: string | null;
  /**
   * Is Datacenter
   */
  is_datacenter?: boolean;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Used
   */
  used: number;
  /**
   * Capacity
   */
  capacity: number;
  /**
   * Free
   */
  free: number;
};

/**
 * RemoveChannelRequest
 */
export type RemoveChannelRequest = {
  /**
   * Channel
   */
  channel: string;
};

/**
 * RetryPairRequest
 *
 * Operator retry of one (account, channel) challenge — the captcha «Решить».
 */
export type RetryPairRequest = {
  /**
   * Account Id
   */
  account_id: string;
  /**
   * Channel
   */
  channel: string;
};

/**
 * SolverToggleRequest
 *
 * Turn the per-campaign challenge (captcha) solver on/off.
 */
export type SolverToggleRequest = {
  /**
   * Enabled
   */
  enabled: boolean;
};

/**
 * SpamStatusVerdict
 *
 * Parsed, cacheable spam-status verdict for one account.
 */
export type SpamStatusVerdict = {
  /**
   * Account Id
   */
  account_id: string;
  /**
   * Status
   */
  status: 'clean' | 'limited' | 'unknown';
  /**
   * Detail
   */
  detail?: string | null;
  /**
   * Checked At
   */
  checked_at: string;
};

/**
 * StartNeurocommentRequest
 *
 * Start the fleet listener on the given account.
 */
export type StartNeurocommentRequest = {
  /**
   * Listener Account Id
   */
  listener_account_id: string;
};

/**
 * StartWarmingRequest
 */
export type StartWarmingRequest = {
  /**
   * Account Id
   */
  account_id: string;
};

/**
 * StopWarmingRequest
 */
export type StopWarmingRequest = {
  /**
   * Account Id
   */
  account_id: string;
};

/**
 * StoryRemoveRequest
 */
export type StoryRemoveRequest = {
  /**
   * Story Id
   */
  story_id: number;
};

/**
 * SubmitCodeRequest
 *
 * API body for ``POST /accounts/{id}/submit-code``.
 */
export type SubmitCodeRequest = {
  /**
   * Code
   */
  code: string;
  /**
   * Password
   */
  password?: string | null;
};

/**
 * TdataImportResult
 *
 * Outcome of one :func:`services.accounts.sessions.import_account_tdata` call.
 *
 * Wrapping the imported accounts in a model (instead of returning a raw
 * ``list[AccountRead]``) keeps the service boundary Pydantic-only, leaves room
 * to add per-import metadata (counts, partial-failure summaries) without
 * breaking every call site, and matches the convention used by ``list_accounts``
 * and other multi-row reads.
 */
export type TdataImportResult = {
  /**
   * Accounts
   */
  accounts?: Array<AccountRead>;
};

/**
 * UpdatePromptRequest
 *
 * Replace a campaign's generation prompt (the edit-prompt modal).
 */
export type UpdatePromptRequest = {
  /**
   * Prompt
   */
  prompt: string;
};

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Username
   */
  username: string;
  /**
   * Role
   */
  role: 'admin';
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * WarmedAccount
 *
 * A graduated (operator-promoted) account, for the warming page's warmed card.
 */
export type WarmedAccount = {
  /**
   * Account Id
   */
  account_id: string;
  /**
   * Label
   */
  label: string;
  /**
   * Warming Days
   */
  warming_days: number;
  /**
   * Phone
   */
  phone?: string | null;
  /**
   * Phone Country
   */
  phone_country?: string | null;
  /**
   * Proxy Type
   */
  proxy_type?: string | null;
  /**
   * Trust Score
   */
  trust_score?: number | null;
  /**
   * Target Days
   */
  target_days: number;
};

/**
 * WarmedAccountList
 *
 * Wrapper for a bulk read of warmed accounts (non-negotiable #2).
 */
export type WarmedAccountList = {
  /**
   * Accounts
   */
  accounts?: Array<WarmedAccount>;
};

/**
 * WarmingAccountState
 *
 * One account's warming status, rendered as a kanban card.
 */
export type WarmingAccountState = {
  /**
   * Account Id
   */
  account_id: string;
  /**
   * Label
   */
  label: string;
  /**
   * State
   */
  state: 'idle' | 'active' | 'sleeping' | 'flood_wait' | 'quarantine' | 'error';
  /**
   * Health
   */
  health: 'idle' | 'ok' | 'warn' | 'fail';
  /**
   * Cycles Completed
   */
  cycles_completed?: number;
  /**
   * Last Event
   */
  last_event?: string | null;
  /**
   * Last Cycle At
   */
  last_cycle_at?: string | null;
  /**
   * Next Run At
   */
  next_run_at?: string | null;
  /**
   * Updated At
   */
  updated_at?: string | null;
  /**
   * Last Error
   */
  last_error?: string | null;
  /**
   * Last Action
   */
  last_action?: string | null;
  /**
   * Last Channel
   */
  last_channel?: string | null;
  /**
   * Heartbeat At
   */
  heartbeat_at?: string | null;
  /**
   * Started At
   */
  started_at?: string | null;
  /**
   * Stopped At
   */
  stopped_at?: string | null;
  /**
   * Flood Wait Seconds
   */
  flood_wait_seconds?: number | null;
  /**
   * Flood Wait Until
   */
  flood_wait_until?: string | null;
  /**
   * Proxy Snapshot
   */
  proxy_snapshot?: string | null;
  /**
   * Daily Actions
   */
  daily_actions?: number;
  /**
   * Daily Count Date
   */
  daily_count_date?: string | null;
  /**
   * Quarantine Count
   */
  quarantine_count?: number;
  /**
   * Trust Score
   */
  trust_score?: number | null;
  /**
   * Trust Band
   */
  trust_band?: string | null;
  /**
   * Trust Reasons
   */
  trust_reasons?: Array<string>;
  /**
   * Spam Status
   */
  spam_status?: string | null;
  /**
   * Spam Detail
   */
  spam_detail?: string | null;
  /**
   * Age Hours
   */
  age_hours?: number | null;
  /**
   * Dm Allowed
   */
  dm_allowed?: boolean;
  /**
   * Phone Country
   */
  phone_country?: string | null;
  /**
   * Proxy Country
   */
  proxy_country?: string | null;
  /**
   * Phone
   */
  phone?: string | null;
  /**
   * Proxy Type
   */
  proxy_type?: string | null;
  /**
   * Phase
   */
  phase?: 'intro' | 'settling' | 'warming' | 'active' | 'warmed' | null;
  /**
   * Phase Label
   */
  phase_label?: string | null;
  /**
   * Daily Cap
   */
  daily_cap?: number;
  /**
   * Progress To Next
   */
  progress_to_next?: number | null;
  /**
   * Days To Next Phase
   */
  days_to_next_phase?: number | null;
  /**
   * Warming Days
   */
  warming_days?: number | null;
  readiness?: WarmingReadiness | null;
  /**
   * Promoted To Nc
   */
  promoted_to_nc?: boolean;
};

/**
 * WarmingBoardState
 *
 * Everything the warming page renders in one poll tick.
 */
export type WarmingBoardState = {
  /**
   * Idle
   */
  idle?: Array<WarmingAccountState>;
  /**
   * Warming
   */
  warming?: Array<WarmingAccountState>;
  channels: WarmingChannelList;
  settings: WarmingSettings;
  /**
   * Channel Count
   */
  channel_count: number;
  /**
   * Active Count
   */
  active_count: number;
  summary?: WarmingSummary;
};

/**
 * WarmingChannel
 *
 * One channel the warming engine can join / read / react in.
 */
export type WarmingChannel = {
  /**
   * Channel
   */
  channel: string;
  /**
   * Label
   */
  label?: string | null;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * WarmingChannelList
 */
export type WarmingChannelList = {
  /**
   * Channels
   */
  channels?: Array<WarmingChannel>;
};

/**
 * WarmingReadiness
 *
 * Pre-start verdict for an account: can it safely begin warming?
 *
 * ``reasons`` is empty iff ``ready`` is True — each entry is a short,
 * human-readable blocker (``"session new"``, ``"no proxy"``, ``"no channels"``).
 */
export type WarmingReadiness = {
  /**
   * Ready
   */
  ready: boolean;
  /**
   * Reasons
   */
  reasons?: Array<string>;
};

/**
 * WarmingSettings
 *
 * Masked, UI-facing warming settings — never carries the raw Gemini key.
 */
export type WarmingSettings = {
  /**
   * Inter Account Chat
   */
  inter_account_chat?: boolean;
  /**
   * Reactions Enabled
   */
  reactions_enabled?: boolean;
  /**
   * Join Enabled
   */
  join_enabled?: boolean;
  /**
   * Enforce Readiness
   */
  enforce_readiness?: boolean;
  /**
   * Quiet Hours Enabled
   */
  quiet_hours_enabled?: boolean;
  /**
   * Quiet Hours Start
   */
  quiet_hours_start?: number;
  /**
   * Quiet Hours End
   */
  quiet_hours_end?: number;
  /**
   * Max Daily Actions
   */
  max_daily_actions?: number;
  /**
   * Has Gemini Key
   */
  has_gemini_key?: boolean;
  /**
   * Gemini Model
   */
  gemini_model: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * WarmingSettingsUpdate
 *
 * Caller-supplied settings change from the UI.
 *
 * ``gemini_api_key`` semantics: ``None`` leaves the stored key untouched, an
 * empty string clears it, any other value replaces it. Same applies to
 * ``gemini_model`` — ``None`` keeps current value, non-empty overrides.
 * An explicit ``clear_gemini_key`` flag is provided so the UI can clear the
 * stored key without ambiguity.
 */
export type WarmingSettingsUpdate = {
  /**
   * Inter Account Chat
   */
  inter_account_chat?: boolean;
  /**
   * Reactions Enabled
   */
  reactions_enabled?: boolean;
  /**
   * Join Enabled
   */
  join_enabled?: boolean;
  /**
   * Enforce Readiness
   */
  enforce_readiness?: boolean;
  /**
   * Quiet Hours Enabled
   */
  quiet_hours_enabled?: boolean;
  /**
   * Quiet Hours Start
   */
  quiet_hours_start?: number;
  /**
   * Quiet Hours End
   */
  quiet_hours_end?: number;
  /**
   * Max Daily Actions
   */
  max_daily_actions?: number;
  /**
   * Gemini Api Key
   */
  gemini_api_key?: string | null;
  /**
   * Gemini Model
   */
  gemini_model?: string | null;
  /**
   * Clear Gemini Key
   */
  clear_gemini_key?: boolean;
};

/**
 * WarmingSummary
 *
 * Fleet-level roll-up shown at the top of the warming page.
 */
export type WarmingSummary = {
  /**
   * Total
   */
  total?: number;
  /**
   * Warming
   */
  warming?: number;
  /**
   * Active
   */
  active?: number;
  /**
   * Ready
   */
  ready?: number;
  /**
   * Attention
   */
  attention?: number;
  /**
   * Trust Healthy
   */
  trust_healthy?: number;
  /**
   * Trust Watch
   */
  trust_watch?: number;
  /**
   * Trust Risk
   */
  trust_risk?: number;
};

export type LoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/login';
};

export type LoginErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/me';
};

export type GetMeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/health';
};

export type GetHealthResponses = {
  /**
   * Successful Response
   */
  200: HealthStatus;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type ListAccountsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Query
     */
    query?: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Cursor
     */
    cursor?: string | null;
    /**
     * Limit
     */
    limit?: number;
  };
  url: '/api/v1/accounts';
};

export type ListAccountsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListAccountsError = ListAccountsErrors[keyof ListAccountsErrors];

export type ListAccountsResponses = {
  /**
   * Successful Response
   */
  200: PageAccountRead;
};

export type ListAccountsResponse = ListAccountsResponses[keyof ListAccountsResponses];

export type CheckAccountData = {
  body: AccountCheckRequest;
  path?: never;
  query?: never;
  url: '/api/v1/accounts/check';
};

export type CheckAccountErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CheckAccountError = CheckAccountErrors[keyof CheckAccountErrors];

export type CheckAccountResponses = {
  /**
   * Successful Response
   */
  200: AccountRead;
};

export type CheckAccountResponse = CheckAccountResponses[keyof CheckAccountResponses];

export type SpamCheckAccountData = {
  body?: never;
  path: {
    /**
     * Account Id
     */
    account_id: string;
  };
  query?: never;
  url: '/api/v1/accounts/{account_id}/spam-check';
};

export type SpamCheckAccountErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SpamCheckAccountError = SpamCheckAccountErrors[keyof SpamCheckAccountErrors];

export type SpamCheckAccountResponses = {
  /**
   * Successful Response
   */
  200: SpamStatusVerdict;
};

export type SpamCheckAccountResponse = SpamCheckAccountResponses[keyof SpamCheckAccountResponses];

export type RequestLoginCodeData = {
  body?: never;
  path: {
    /**
     * Account Id
     */
    account_id: string;
  };
  query?: never;
  url: '/api/v1/accounts/{account_id}/request-code';
};

export type RequestLoginCodeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RequestLoginCodeError = RequestLoginCodeErrors[keyof RequestLoginCodeErrors];

export type RequestLoginCodeResponses = {
  /**
   * Successful Response
   */
  200: PhoneCodeRequestResult;
};

export type RequestLoginCodeResponse = RequestLoginCodeResponses[keyof RequestLoginCodeResponses];

export type SubmitLoginCodeData = {
  body: SubmitCodeRequest;
  path: {
    /**
     * Account Id
     */
    account_id: string;
  };
  query?: never;
  url: '/api/v1/accounts/{account_id}/submit-code';
};

export type SubmitLoginCodeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SubmitLoginCodeError = SubmitLoginCodeErrors[keyof SubmitLoginCodeErrors];

export type SubmitLoginCodeResponses = {
  /**
   * Successful Response
   */
  200: AccountRead;
};

export type SubmitLoginCodeResponse = SubmitLoginCodeResponses[keyof SubmitLoginCodeResponses];

export type LogoutAccountData = {
  body?: never;
  path: {
    /**
     * Account Id
     */
    account_id: string;
  };
  query?: never;
  url: '/api/v1/accounts/{account_id}/logout';
};

export type LogoutAccountErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LogoutAccountError = LogoutAccountErrors[keyof LogoutAccountErrors];

export type LogoutAccountResponses = {
  /**
   * Successful Response
   */
  200: AccountRead;
};

export type LogoutAccountResponse = LogoutAccountResponses[keyof LogoutAccountResponses];

export type ResetAccountSessionData = {
  body?: never;
  path: {
    /**
     * Account Id
     */
    account_id: string;
  };
  query?: never;
  url: '/api/v1/accounts/{account_id}/reset-session';
};

export type ResetAccountSessionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetAccountSessionError = ResetAccountSessionErrors[keyof ResetAccountSessionErrors];

export type ResetAccountSessionResponses = {
  /**
   * Successful Response
   */
  200: AccountRead;
};

export type ResetAccountSessionResponse =
  ResetAccountSessionResponses[keyof ResetAccountSessionResponses];

export type UpdateAccountProfileData = {
  body: AccountProfileUpdateRequest;
  path?: never;
  query?: never;
  url: '/api/v1/accounts/profile';
};

export type UpdateAccountProfileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateAccountProfileError =
  UpdateAccountProfileErrors[keyof UpdateAccountProfileErrors];

export type UpdateAccountProfileResponses = {
  /**
   * Successful Response
   */
  200: AccountRead;
};

export type UpdateAccountProfileResponse =
  UpdateAccountProfileResponses[keyof UpdateAccountProfileResponses];

export type DeleteAccountData = {
  body?: never;
  path: {
    /**
     * Account Id
     */
    account_id: string;
  };
  query?: never;
  url: '/api/v1/accounts/{account_id}';
};

export type DeleteAccountErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type ImportAccountTdataData = {
  body: BodyImportAccountTdata;
  path?: never;
  query?: never;
  url: '/api/v1/accounts/import-tdata';
};

export type ImportAccountTdataErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ImportAccountTdataError = ImportAccountTdataErrors[keyof ImportAccountTdataErrors];

export type ImportAccountTdataResponses = {
  /**
   * Successful Response
   */
  200: TdataImportResult;
};

export type ImportAccountTdataResponse =
  ImportAccountTdataResponses[keyof ImportAccountTdataResponses];

export type ImportAccountSessionData = {
  body: BodyImportAccountSession;
  path?: never;
  query?: never;
  url: '/api/v1/accounts/import-session';
};

export type ImportAccountSessionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ImportAccountSessionError =
  ImportAccountSessionErrors[keyof ImportAccountSessionErrors];

export type ImportAccountSessionResponses = {
  /**
   * Successful Response
   */
  200: AccountRead;
};

export type ImportAccountSessionResponse =
  ImportAccountSessionResponses[keyof ImportAccountSessionResponses];

export type SetAccountPhotoData = {
  body: BodySetAccountPhoto;
  path?: never;
  query?: never;
  url: '/api/v1/accounts/photo';
};

export type SetAccountPhotoErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SetAccountPhotoError = SetAccountPhotoErrors[keyof SetAccountPhotoErrors];

export type SetAccountPhotoResponses = {
  /**
   * Successful Response
   */
  200: ActionResult;
};

export type SetAccountPhotoResponse = SetAccountPhotoResponses[keyof SetAccountPhotoResponses];

export type GetAccountProfileSnapshotData = {
  body?: never;
  path: {
    /**
     * Account Id
     */
    account_id: string;
  };
  query?: never;
  url: '/api/v1/accounts/{account_id}/profile-snapshot';
};

export type GetAccountProfileSnapshotErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAccountProfileSnapshotError =
  GetAccountProfileSnapshotErrors[keyof GetAccountProfileSnapshotErrors];

export type GetAccountProfileSnapshotResponses = {
  /**
   * Successful Response
   */
  200: AccountProfileView;
};

export type GetAccountProfileSnapshotResponse =
  GetAccountProfileSnapshotResponses[keyof GetAccountProfileSnapshotResponses];

export type PostAccountStoryData = {
  body: BodyPostAccountStory;
  path: {
    /**
     * Account Id
     */
    account_id: string;
  };
  query?: never;
  url: '/api/v1/accounts/{account_id}/story';
};

export type PostAccountStoryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PostAccountStoryError = PostAccountStoryErrors[keyof PostAccountStoryErrors];

export type PostAccountStoryResponses = {
  /**
   * Successful Response
   */
  200: ActionResult;
};

export type PostAccountStoryResponse = PostAccountStoryResponses[keyof PostAccountStoryResponses];

export type AddAccountMusicData = {
  body: BodyAddAccountMusic;
  path: {
    /**
     * Account Id
     */
    account_id: string;
  };
  query?: never;
  url: '/api/v1/accounts/{account_id}/music';
};

export type AddAccountMusicErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddAccountMusicError = AddAccountMusicErrors[keyof AddAccountMusicErrors];

export type AddAccountMusicResponses = {
  /**
   * Successful Response
   */
  200: ActionResult;
};

export type AddAccountMusicResponse = AddAccountMusicResponses[keyof AddAccountMusicResponses];

export type RemoveAccountStoryData = {
  body: StoryRemoveRequest;
  path: {
    /**
     * Account Id
     */
    account_id: string;
  };
  query?: never;
  url: '/api/v1/accounts/{account_id}/story/remove';
};

export type RemoveAccountStoryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RemoveAccountStoryError = RemoveAccountStoryErrors[keyof RemoveAccountStoryErrors];

export type RemoveAccountStoryResponses = {
  /**
   * Successful Response
   */
  200: ActionResult;
};

export type RemoveAccountStoryResponse =
  RemoveAccountStoryResponses[keyof RemoveAccountStoryResponses];

export type RemoveAccountMusicData = {
  body: MusicRemoveRequest;
  path: {
    /**
     * Account Id
     */
    account_id: string;
  };
  query?: never;
  url: '/api/v1/accounts/{account_id}/music/remove';
};

export type RemoveAccountMusicErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RemoveAccountMusicError = RemoveAccountMusicErrors[keyof RemoveAccountMusicErrors];

export type RemoveAccountMusicResponses = {
  /**
   * Successful Response
   */
  200: ActionResult;
};

export type RemoveAccountMusicResponse =
  RemoveAccountMusicResponses[keyof RemoveAccountMusicResponses];

export type RemoveAccountPhotoData = {
  body: PhotoRemoveRequest;
  path: {
    /**
     * Account Id
     */
    account_id: string;
  };
  query?: never;
  url: '/api/v1/accounts/{account_id}/photo/remove';
};

export type RemoveAccountPhotoErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RemoveAccountPhotoError = RemoveAccountPhotoErrors[keyof RemoveAccountPhotoErrors];

export type RemoveAccountPhotoResponses = {
  /**
   * Successful Response
   */
  200: ActionResult;
};

export type RemoveAccountPhotoResponse =
  RemoveAccountPhotoResponses[keyof RemoveAccountPhotoResponses];

export type ListProxiesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/proxies';
};

export type ListProxiesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListProxiesError = ListProxiesErrors[keyof ListProxiesErrors];

export type ListProxiesResponses = {
  /**
   * Successful Response
   */
  200: ProxyList;
};

export type ListProxiesResponse = ListProxiesResponses[keyof ListProxiesResponses];

export type CreateProxyData = {
  body: ProxyCreate;
  path?: never;
  query?: never;
  url: '/api/v1/proxies';
};

export type CreateProxyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateProxyError = CreateProxyErrors[keyof CreateProxyErrors];

export type CreateProxyResponses = {
  /**
   * Successful Response
   */
  200: ProxyRead;
};

export type CreateProxyResponse = CreateProxyResponses[keyof CreateProxyResponses];

export type ProbeProxyData = {
  body: ProxyCreate;
  path?: never;
  query?: never;
  url: '/api/v1/proxies/probe';
};

export type ProbeProxyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProbeProxyError = ProbeProxyErrors[keyof ProbeProxyErrors];

export type ProbeProxyResponses = {
  /**
   * Successful Response
   */
  200: ProxyCheckResult;
};

export type ProbeProxyResponse = ProbeProxyResponses[keyof ProbeProxyResponses];

export type CheckProxyData = {
  body?: never;
  path: {
    /**
     * Proxy Id
     */
    proxy_id: string;
  };
  query?: never;
  url: '/api/v1/proxies/{proxy_id}/check';
};

export type CheckProxyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CheckProxyError = CheckProxyErrors[keyof CheckProxyErrors];

export type CheckProxyResponses = {
  /**
   * Successful Response
   */
  200: ProxyRead;
};

export type CheckProxyResponse = CheckProxyResponses[keyof CheckProxyResponses];

export type AssignProxyData = {
  body: ProxyAssignRequest;
  path: {
    /**
     * Proxy Id
     */
    proxy_id: string;
  };
  query?: never;
  url: '/api/v1/proxies/{proxy_id}/assign';
};

export type AssignProxyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AssignProxyError = AssignProxyErrors[keyof AssignProxyErrors];

export type AssignProxyResponses = {
  /**
   * Successful Response
   */
  200: ProxyRead;
};

export type AssignProxyResponse = AssignProxyResponses[keyof AssignProxyResponses];

export type UnassignProxyData = {
  body: ProxyAssignRequest;
  path?: never;
  query?: never;
  url: '/api/v1/proxies/unassign';
};

export type UnassignProxyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UnassignProxyError = UnassignProxyErrors[keyof UnassignProxyErrors];

export type UnassignProxyResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type UnassignProxyResponse = UnassignProxyResponses[keyof UnassignProxyResponses];

export type DeleteProxyData = {
  body?: never;
  path: {
    /**
     * Proxy Id
     */
    proxy_id: string;
  };
  query?: never;
  url: '/api/v1/proxies/{proxy_id}';
};

export type DeleteProxyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteProxyError = DeleteProxyErrors[keyof DeleteProxyErrors];

export type DeleteProxyResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteProxyResponse = DeleteProxyResponses[keyof DeleteProxyResponses];

export type GetWarmingBoardData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/warming/board';
};

export type GetWarmingBoardErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetWarmingBoardError = GetWarmingBoardErrors[keyof GetWarmingBoardErrors];

export type GetWarmingBoardResponses = {
  /**
   * Successful Response
   */
  200: WarmingBoardState;
};

export type GetWarmingBoardResponse = GetWarmingBoardResponses[keyof GetWarmingBoardResponses];

export type ListWarmedAccountsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/warming/warmed';
};

export type ListWarmedAccountsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListWarmedAccountsError = ListWarmedAccountsErrors[keyof ListWarmedAccountsErrors];

export type ListWarmedAccountsResponses = {
  /**
   * Successful Response
   */
  200: WarmedAccountList;
};

export type ListWarmedAccountsResponse =
  ListWarmedAccountsResponses[keyof ListWarmedAccountsResponses];

export type PromoteToNeurocommentData = {
  body: PromoteRequest;
  path?: never;
  query?: never;
  url: '/api/v1/warming/promote';
};

export type PromoteToNeurocommentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PromoteToNeurocommentError =
  PromoteToNeurocommentErrors[keyof PromoteToNeurocommentErrors];

export type PromoteToNeurocommentResponses = {
  /**
   * Successful Response
   */
  200: WarmingAccountState;
};

export type PromoteToNeurocommentResponse =
  PromoteToNeurocommentResponses[keyof PromoteToNeurocommentResponses];

export type UnpromoteFromNeurocommentData = {
  body: PromoteRequest;
  path?: never;
  query?: never;
  url: '/api/v1/warming/unpromote';
};

export type UnpromoteFromNeurocommentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UnpromoteFromNeurocommentError =
  UnpromoteFromNeurocommentErrors[keyof UnpromoteFromNeurocommentErrors];

export type UnpromoteFromNeurocommentResponses = {
  /**
   * Successful Response
   */
  200: WarmingAccountState;
};

export type UnpromoteFromNeurocommentResponse =
  UnpromoteFromNeurocommentResponses[keyof UnpromoteFromNeurocommentResponses];

export type StartWarmingData = {
  body: StartWarmingRequest;
  path?: never;
  query?: never;
  url: '/api/v1/warming/start';
};

export type StartWarmingErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type StartWarmingError = StartWarmingErrors[keyof StartWarmingErrors];

export type StartWarmingResponses = {
  /**
   * Successful Response
   */
  200: WarmingAccountState;
};

export type StartWarmingResponse = StartWarmingResponses[keyof StartWarmingResponses];

export type StopWarmingData = {
  body: StopWarmingRequest;
  path?: never;
  query?: never;
  url: '/api/v1/warming/stop';
};

export type StopWarmingErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type StopWarmingError = StopWarmingErrors[keyof StopWarmingErrors];

export type StopWarmingResponses = {
  /**
   * Successful Response
   */
  200: WarmingAccountState;
};

export type StopWarmingResponse = StopWarmingResponses[keyof StopWarmingResponses];

export type ListWarmingChannelsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/warming/channels';
};

export type ListWarmingChannelsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListWarmingChannelsError = ListWarmingChannelsErrors[keyof ListWarmingChannelsErrors];

export type ListWarmingChannelsResponses = {
  /**
   * Successful Response
   */
  200: WarmingChannelList;
};

export type ListWarmingChannelsResponse =
  ListWarmingChannelsResponses[keyof ListWarmingChannelsResponses];

export type AddWarmingChannelsData = {
  body: AddChannelsRequest;
  path?: never;
  query?: never;
  url: '/api/v1/warming/channels';
};

export type AddWarmingChannelsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddWarmingChannelsError = AddWarmingChannelsErrors[keyof AddWarmingChannelsErrors];

export type AddWarmingChannelsResponses = {
  /**
   * Successful Response
   */
  200: WarmingChannelList;
};

export type AddWarmingChannelsResponse =
  AddWarmingChannelsResponses[keyof AddWarmingChannelsResponses];

export type RemoveWarmingChannelData = {
  body: RemoveChannelRequest;
  path?: never;
  query?: never;
  url: '/api/v1/warming/channels/remove';
};

export type RemoveWarmingChannelErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RemoveWarmingChannelError =
  RemoveWarmingChannelErrors[keyof RemoveWarmingChannelErrors];

export type RemoveWarmingChannelResponses = {
  /**
   * Successful Response
   */
  200: WarmingChannelList;
};

export type RemoveWarmingChannelResponse =
  RemoveWarmingChannelResponses[keyof RemoveWarmingChannelResponses];

export type GetWarmingSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/warming/settings';
};

export type GetWarmingSettingsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetWarmingSettingsError = GetWarmingSettingsErrors[keyof GetWarmingSettingsErrors];

export type GetWarmingSettingsResponses = {
  /**
   * Successful Response
   */
  200: WarmingSettings;
};

export type GetWarmingSettingsResponse =
  GetWarmingSettingsResponses[keyof GetWarmingSettingsResponses];

export type UpdateWarmingSettingsData = {
  body: WarmingSettingsUpdate;
  path?: never;
  query?: never;
  url: '/api/v1/warming/settings';
};

export type UpdateWarmingSettingsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateWarmingSettingsError =
  UpdateWarmingSettingsErrors[keyof UpdateWarmingSettingsErrors];

export type UpdateWarmingSettingsResponses = {
  /**
   * Successful Response
   */
  200: WarmingSettings;
};

export type UpdateWarmingSettingsResponse =
  UpdateWarmingSettingsResponses[keyof UpdateWarmingSettingsResponses];

export type ListCampaignsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/neurocomment/campaigns';
};

export type ListCampaignsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListCampaignsError = ListCampaignsErrors[keyof ListCampaignsErrors];

export type ListCampaignsResponses = {
  /**
   * Successful Response
   */
  200: CampaignList;
};

export type ListCampaignsResponse = ListCampaignsResponses[keyof ListCampaignsResponses];

export type CreateCampaignData = {
  body: CampaignCreate;
  path?: never;
  query?: never;
  url: '/api/v1/neurocomment/campaigns';
};

export type CreateCampaignErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCampaignError = CreateCampaignErrors[keyof CreateCampaignErrors];

export type CreateCampaignResponses = {
  /**
   * Successful Response
   */
  200: NeurocommentCampaign;
};

export type CreateCampaignResponse = CreateCampaignResponses[keyof CreateCampaignResponses];

export type GetNeurocommentBoardData = {
  body?: never;
  path: {
    /**
     * Campaign Id
     */
    campaign_id: string;
  };
  query?: never;
  url: '/api/v1/neurocomment/campaigns/{campaign_id}/board';
};

export type GetNeurocommentBoardErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetNeurocommentBoardError =
  GetNeurocommentBoardErrors[keyof GetNeurocommentBoardErrors];

export type GetNeurocommentBoardResponses = {
  /**
   * Successful Response
   */
  200: NeurocommentBoard;
};

export type GetNeurocommentBoardResponse =
  GetNeurocommentBoardResponses[keyof GetNeurocommentBoardResponses];

export type LinkCampaignChannelData = {
  body: LinkChannelRequest;
  path: {
    /**
     * Campaign Id
     */
    campaign_id: string;
  };
  query?: never;
  url: '/api/v1/neurocomment/campaigns/{campaign_id}/channels';
};

export type LinkCampaignChannelErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LinkCampaignChannelError = LinkCampaignChannelErrors[keyof LinkCampaignChannelErrors];

export type LinkCampaignChannelResponses = {
  /**
   * Successful Response
   */
  200: ChannelLinkOutcome;
};

export type LinkCampaignChannelResponse =
  LinkCampaignChannelResponses[keyof LinkCampaignChannelResponses];

export type AssignCampaignAccountData = {
  body: AssignAccountRequest;
  path: {
    /**
     * Campaign Id
     */
    campaign_id: string;
  };
  query?: never;
  url: '/api/v1/neurocomment/campaigns/{campaign_id}/accounts';
};

export type AssignCampaignAccountErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AssignCampaignAccountError =
  AssignCampaignAccountErrors[keyof AssignCampaignAccountErrors];

export type AssignCampaignAccountResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type AssignCampaignAccountResponse =
  AssignCampaignAccountResponses[keyof AssignCampaignAccountResponses];

export type DeleteCampaignData = {
  body?: never;
  path: {
    /**
     * Campaign Id
     */
    campaign_id: string;
  };
  query?: never;
  url: '/api/v1/neurocomment/campaigns/{campaign_id}';
};

export type DeleteCampaignErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCampaignError = DeleteCampaignErrors[keyof DeleteCampaignErrors];

export type DeleteCampaignResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteCampaignResponse = DeleteCampaignResponses[keyof DeleteCampaignResponses];

export type RemoveCampaignChannelData = {
  body: LinkChannelRequest;
  path: {
    /**
     * Campaign Id
     */
    campaign_id: string;
  };
  query?: never;
  url: '/api/v1/neurocomment/campaigns/{campaign_id}/channels/remove';
};

export type RemoveCampaignChannelErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RemoveCampaignChannelError =
  RemoveCampaignChannelErrors[keyof RemoveCampaignChannelErrors];

export type RemoveCampaignChannelResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type RemoveCampaignChannelResponse =
  RemoveCampaignChannelResponses[keyof RemoveCampaignChannelResponses];

export type UpdateCampaignPromptData = {
  body: UpdatePromptRequest;
  path: {
    /**
     * Campaign Id
     */
    campaign_id: string;
  };
  query?: never;
  url: '/api/v1/neurocomment/campaigns/{campaign_id}/prompt';
};

export type UpdateCampaignPromptErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateCampaignPromptError =
  UpdateCampaignPromptErrors[keyof UpdateCampaignPromptErrors];

export type UpdateCampaignPromptResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type UpdateCampaignPromptResponse =
  UpdateCampaignPromptResponses[keyof UpdateCampaignPromptResponses];

export type SetCampaignSolverData = {
  body: SolverToggleRequest;
  path: {
    /**
     * Campaign Id
     */
    campaign_id: string;
  };
  query?: never;
  url: '/api/v1/neurocomment/campaigns/{campaign_id}/solver';
};

export type SetCampaignSolverErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SetCampaignSolverError = SetCampaignSolverErrors[keyof SetCampaignSolverErrors];

export type SetCampaignSolverResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type SetCampaignSolverResponse =
  SetCampaignSolverResponses[keyof SetCampaignSolverResponses];

export type RetryChallengeData = {
  body: RetryPairRequest;
  path?: never;
  query?: never;
  url: '/api/v1/neurocomment/retry';
};

export type RetryChallengeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RetryChallengeError = RetryChallengeErrors[keyof RetryChallengeErrors];

export type RetryChallengeResponses = {
  /**
   * Successful Response
   */
  200: AccountChannelOnboarding;
};

export type RetryChallengeResponse = RetryChallengeResponses[keyof RetryChallengeResponses];

export type ListCampaignChallengesData = {
  body?: never;
  path: {
    /**
     * Campaign Id
     */
    campaign_id: string;
  };
  query?: {
    /**
     * Limit
     */
    limit?: number;
  };
  url: '/api/v1/neurocomment/campaigns/{campaign_id}/challenges';
};

export type ListCampaignChallengesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListCampaignChallengesError =
  ListCampaignChallengesErrors[keyof ListCampaignChallengesErrors];

export type ListCampaignChallengesResponses = {
  /**
   * Successful Response
   */
  200: ChallengeRowList;
};

export type ListCampaignChallengesResponse =
  ListCampaignChallengesResponses[keyof ListCampaignChallengesResponses];

export type GetNeurocommentRuntimeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/neurocomment/runtime';
};

export type GetNeurocommentRuntimeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetNeurocommentRuntimeError =
  GetNeurocommentRuntimeErrors[keyof GetNeurocommentRuntimeErrors];

export type GetNeurocommentRuntimeResponses = {
  /**
   * Successful Response
   */
  200: NeurocommentRuntimeStatus;
};

export type GetNeurocommentRuntimeResponse =
  GetNeurocommentRuntimeResponses[keyof GetNeurocommentRuntimeResponses];

export type StartNeurocommentData = {
  body: StartNeurocommentRequest;
  path?: never;
  query?: never;
  url: '/api/v1/neurocomment/start';
};

export type StartNeurocommentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type StartNeurocommentError = StartNeurocommentErrors[keyof StartNeurocommentErrors];

export type StartNeurocommentResponses = {
  /**
   * Successful Response
   */
  200: NeurocommentRuntimeStatus;
};

export type StartNeurocommentResponse =
  StartNeurocommentResponses[keyof StartNeurocommentResponses];

export type StopNeurocommentData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/neurocomment/stop';
};

export type StopNeurocommentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type StopNeurocommentError = StopNeurocommentErrors[keyof StopNeurocommentErrors];

export type StopNeurocommentResponses = {
  /**
   * Successful Response
   */
  200: NeurocommentRuntimeStatus;
};

export type StopNeurocommentResponse = StopNeurocommentResponses[keyof StopNeurocommentResponses];

export type GetNeurocommentSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/neurocomment/settings';
};

export type GetNeurocommentSettingsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetNeurocommentSettingsError =
  GetNeurocommentSettingsErrors[keyof GetNeurocommentSettingsErrors];

export type GetNeurocommentSettingsResponses = {
  /**
   * Successful Response
   */
  200: NeurocommentSettings;
};

export type GetNeurocommentSettingsResponse =
  GetNeurocommentSettingsResponses[keyof GetNeurocommentSettingsResponses];

export type UpdateNeurocommentSettingsData = {
  body: NeurocommentSettingsUpdate;
  path?: never;
  query?: never;
  url: '/api/v1/neurocomment/settings';
};

export type UpdateNeurocommentSettingsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateNeurocommentSettingsError =
  UpdateNeurocommentSettingsErrors[keyof UpdateNeurocommentSettingsErrors];

export type UpdateNeurocommentSettingsResponses = {
  /**
   * Successful Response
   */
  200: NeurocommentSettings;
};

export type UpdateNeurocommentSettingsResponse =
  UpdateNeurocommentSettingsResponses[keyof UpdateNeurocommentSettingsResponses];

export type ListLogsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Status
     */
    status?: 'all' | 'success' | 'warning' | 'error';
    /**
     * Account Id
     */
    account_id?: string;
    /**
     * Event Prefix
     */
    event_prefix?: string;
    /**
     * Cursor
     */
    cursor?: string | null;
    /**
     * Limit
     */
    limit?: number;
  };
  url: '/api/v1/logs';
};

export type ListLogsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListLogsError = ListLogsErrors[keyof ListLogsErrors];

export type ListLogsResponses = {
  /**
   * Successful Response
   */
  200: PageLogEntry;
};

export type ListLogsResponse = ListLogsResponses[keyof ListLogsResponses];
