// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from '@tanstack/react-query';

import { client } from '../client.gen';
import {
  addWarmingChannels,
  assignCampaignAccount,
  assignProxy,
  checkAccount,
  checkProxy,
  createCampaign,
  createProxy,
  deleteAccount,
  deleteProxy,
  getHealth,
  getMe,
  getNeurocommentBoard,
  getNeurocommentRuntime,
  getWarmingBoard,
  getWarmingSettings,
  importAccountTdata,
  linkCampaignChannel,
  listAccounts,
  listCampaignChallenges,
  listCampaigns,
  listLogs,
  listProxies,
  listWarmingChannels,
  login,
  logout,
  logoutAccount,
  type Options,
  probeProxy,
  removeWarmingChannel,
  requestLoginCode,
  resetAccountSession,
  setAccountPhoto,
  spamCheckAccount,
  startNeurocomment,
  startWarming,
  stopNeurocomment,
  stopWarming,
  submitLoginCode,
  unassignProxy,
  updateAccountProfile,
  updateWarmingSettings,
} from '../sdk.gen';
import type {
  AddWarmingChannelsData,
  AddWarmingChannelsError,
  AddWarmingChannelsResponse,
  AssignCampaignAccountData,
  AssignCampaignAccountError,
  AssignCampaignAccountResponse,
  AssignProxyData,
  AssignProxyError,
  AssignProxyResponse,
  CheckAccountData,
  CheckAccountError,
  CheckAccountResponse,
  CheckProxyData,
  CheckProxyError,
  CheckProxyResponse,
  CreateCampaignData,
  CreateCampaignError,
  CreateCampaignResponse,
  CreateProxyData,
  CreateProxyError,
  CreateProxyResponse,
  DeleteAccountData,
  DeleteAccountError,
  DeleteAccountResponse,
  DeleteProxyData,
  DeleteProxyError,
  DeleteProxyResponse,
  GetHealthData,
  GetHealthResponse,
  GetMeData,
  GetMeError,
  GetMeResponse,
  GetNeurocommentBoardData,
  GetNeurocommentBoardError,
  GetNeurocommentBoardResponse,
  GetNeurocommentRuntimeData,
  GetNeurocommentRuntimeError,
  GetNeurocommentRuntimeResponse,
  GetWarmingBoardData,
  GetWarmingBoardError,
  GetWarmingBoardResponse,
  GetWarmingSettingsData,
  GetWarmingSettingsError,
  GetWarmingSettingsResponse,
  ImportAccountTdataData,
  ImportAccountTdataError,
  ImportAccountTdataResponse,
  LinkCampaignChannelData,
  LinkCampaignChannelError,
  LinkCampaignChannelResponse,
  ListAccountsData,
  ListAccountsError,
  ListAccountsResponse,
  ListCampaignChallengesData,
  ListCampaignChallengesError,
  ListCampaignChallengesResponse,
  ListCampaignsData,
  ListCampaignsError,
  ListCampaignsResponse,
  ListLogsData,
  ListLogsError,
  ListLogsResponse,
  ListProxiesData,
  ListProxiesError,
  ListProxiesResponse,
  ListWarmingChannelsData,
  ListWarmingChannelsError,
  ListWarmingChannelsResponse,
  LoginData,
  LoginError,
  LoginResponse,
  LogoutAccountData,
  LogoutAccountError,
  LogoutAccountResponse,
  LogoutData,
  LogoutResponse,
  ProbeProxyData,
  ProbeProxyError,
  ProbeProxyResponse,
  RemoveWarmingChannelData,
  RemoveWarmingChannelError,
  RemoveWarmingChannelResponse,
  RequestLoginCodeData,
  RequestLoginCodeError,
  RequestLoginCodeResponse,
  ResetAccountSessionData,
  ResetAccountSessionError,
  ResetAccountSessionResponse,
  SetAccountPhotoData,
  SetAccountPhotoError,
  SetAccountPhotoResponse,
  SpamCheckAccountData,
  SpamCheckAccountError,
  SpamCheckAccountResponse,
  StartNeurocommentData,
  StartNeurocommentError,
  StartNeurocommentResponse,
  StartWarmingData,
  StartWarmingError,
  StartWarmingResponse,
  StopNeurocommentData,
  StopNeurocommentError,
  StopNeurocommentResponse,
  StopWarmingData,
  StopWarmingError,
  StopWarmingResponse,
  SubmitLoginCodeData,
  SubmitLoginCodeError,
  SubmitLoginCodeResponse,
  UnassignProxyData,
  UnassignProxyError,
  UnassignProxyResponse,
  UpdateAccountProfileData,
  UpdateAccountProfileError,
  UpdateAccountProfileResponse,
  UpdateWarmingSettingsData,
  UpdateWarmingSettingsError,
  UpdateWarmingSettingsResponse,
} from '../types.gen';

/**
 * Login
 */
export const loginMutation = (
  options?: Partial<Options<LoginData>>,
): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
  const mutationOptions: UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await login({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Logout
 */
export const logoutMutation = (
  options?: Partial<Options<LogoutData>>,
): UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> => {
  const mutationOptions: UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await logout({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getMeQueryKey = (options?: Options<GetMeData>) => createQueryKey('getMe', options);

/**
 * Me
 */
export const getMeOptions = (options?: Options<GetMeData>) =>
  queryOptions<GetMeResponse, GetMeError, GetMeResponse, ReturnType<typeof getMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMeQueryKey(options),
  });

export const getHealthQueryKey = (options?: Options<GetHealthData>) =>
  createQueryKey('getHealth', options);

/**
 * Health
 */
export const getHealthOptions = (options?: Options<GetHealthData>) =>
  queryOptions<
    GetHealthResponse,
    DefaultError,
    GetHealthResponse,
    ReturnType<typeof getHealthQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHealth({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHealthQueryKey(options),
  });

export const listAccountsQueryKey = (options?: Options<ListAccountsData>) =>
  createQueryKey('listAccounts', options);

/**
 * List Accounts
 */
export const listAccountsOptions = (options?: Options<ListAccountsData>) =>
  queryOptions<
    ListAccountsResponse,
    ListAccountsError,
    ListAccountsResponse,
    ReturnType<typeof listAccountsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAccounts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listAccountsQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const listAccountsInfiniteQueryKey = (
  options?: Options<ListAccountsData>,
): QueryKey<Options<ListAccountsData>> => createQueryKey('listAccounts', options, true);

/**
 * List Accounts
 */
export const listAccountsInfiniteOptions = (options?: Options<ListAccountsData>) =>
  infiniteQueryOptions<
    ListAccountsResponse,
    ListAccountsError,
    InfiniteData<ListAccountsResponse>,
    QueryKey<Options<ListAccountsData>>,
    | string
    | null
    | Pick<QueryKey<Options<ListAccountsData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListAccountsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listAccounts({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listAccountsInfiniteQueryKey(options),
    },
  );

/**
 * Check Account
 */
export const checkAccountMutation = (
  options?: Partial<Options<CheckAccountData>>,
): UseMutationOptions<CheckAccountResponse, CheckAccountError, Options<CheckAccountData>> => {
  const mutationOptions: UseMutationOptions<
    CheckAccountResponse,
    CheckAccountError,
    Options<CheckAccountData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await checkAccount({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Spam Check Account
 *
 * Re-probe @SpamBot for one account and return the fresh, cached verdict.
 */
export const spamCheckAccountMutation = (
  options?: Partial<Options<SpamCheckAccountData>>,
): UseMutationOptions<
  SpamCheckAccountResponse,
  SpamCheckAccountError,
  Options<SpamCheckAccountData>
> => {
  const mutationOptions: UseMutationOptions<
    SpamCheckAccountResponse,
    SpamCheckAccountError,
    Options<SpamCheckAccountData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await spamCheckAccount({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Request Login Code
 *
 * Send a Telegram login code to the account's phone (re-auth by code).
 */
export const requestLoginCodeMutation = (
  options?: Partial<Options<RequestLoginCodeData>>,
): UseMutationOptions<
  RequestLoginCodeResponse,
  RequestLoginCodeError,
  Options<RequestLoginCodeData>
> => {
  const mutationOptions: UseMutationOptions<
    RequestLoginCodeResponse,
    RequestLoginCodeError,
    Options<RequestLoginCodeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await requestLoginCode({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Submit Login Code
 *
 * Complete sign-in with the SMS code (+ optional 2FA password).
 */
export const submitLoginCodeMutation = (
  options?: Partial<Options<SubmitLoginCodeData>>,
): UseMutationOptions<
  SubmitLoginCodeResponse,
  SubmitLoginCodeError,
  Options<SubmitLoginCodeData>
> => {
  const mutationOptions: UseMutationOptions<
    SubmitLoginCodeResponse,
    SubmitLoginCodeError,
    Options<SubmitLoginCodeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await submitLoginCode({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Logout Account
 *
 * Log the account out server-side and mark it unauthorized.
 */
export const logoutAccountMutation = (
  options?: Partial<Options<LogoutAccountData>>,
): UseMutationOptions<LogoutAccountResponse, LogoutAccountError, Options<LogoutAccountData>> => {
  const mutationOptions: UseMutationOptions<
    LogoutAccountResponse,
    LogoutAccountError,
    Options<LogoutAccountData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await logoutAccount({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Reset Account Session
 *
 * Log out and wipe the local session token so the next login is clean.
 */
export const resetAccountSessionMutation = (
  options?: Partial<Options<ResetAccountSessionData>>,
): UseMutationOptions<
  ResetAccountSessionResponse,
  ResetAccountSessionError,
  Options<ResetAccountSessionData>
> => {
  const mutationOptions: UseMutationOptions<
    ResetAccountSessionResponse,
    ResetAccountSessionError,
    Options<ResetAccountSessionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await resetAccountSession({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Account Profile
 */
export const updateAccountProfileMutation = (
  options?: Partial<Options<UpdateAccountProfileData>>,
): UseMutationOptions<
  UpdateAccountProfileResponse,
  UpdateAccountProfileError,
  Options<UpdateAccountProfileData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateAccountProfileResponse,
    UpdateAccountProfileError,
    Options<UpdateAccountProfileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateAccountProfile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Account
 */
export const deleteAccountMutation = (
  options?: Partial<Options<DeleteAccountData>>,
): UseMutationOptions<DeleteAccountResponse, DeleteAccountError, Options<DeleteAccountData>> => {
  const mutationOptions: UseMutationOptions<
    DeleteAccountResponse,
    DeleteAccountError,
    Options<DeleteAccountData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteAccount({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Import Account Tdata
 */
export const importAccountTdataMutation = (
  options?: Partial<Options<ImportAccountTdataData>>,
): UseMutationOptions<
  ImportAccountTdataResponse,
  ImportAccountTdataError,
  Options<ImportAccountTdataData>
> => {
  const mutationOptions: UseMutationOptions<
    ImportAccountTdataResponse,
    ImportAccountTdataError,
    Options<ImportAccountTdataData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await importAccountTdata({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Set Account Photo
 */
export const setAccountPhotoMutation = (
  options?: Partial<Options<SetAccountPhotoData>>,
): UseMutationOptions<
  SetAccountPhotoResponse,
  SetAccountPhotoError,
  Options<SetAccountPhotoData>
> => {
  const mutationOptions: UseMutationOptions<
    SetAccountPhotoResponse,
    SetAccountPhotoError,
    Options<SetAccountPhotoData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await setAccountPhoto({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listProxiesQueryKey = (options?: Options<ListProxiesData>) =>
  createQueryKey('listProxies', options);

/**
 * List Proxies
 */
export const listProxiesOptions = (options?: Options<ListProxiesData>) =>
  queryOptions<
    ListProxiesResponse,
    ListProxiesError,
    ListProxiesResponse,
    ReturnType<typeof listProxiesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listProxies({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listProxiesQueryKey(options),
  });

/**
 * Create Proxy
 */
export const createProxyMutation = (
  options?: Partial<Options<CreateProxyData>>,
): UseMutationOptions<CreateProxyResponse, CreateProxyError, Options<CreateProxyData>> => {
  const mutationOptions: UseMutationOptions<
    CreateProxyResponse,
    CreateProxyError,
    Options<CreateProxyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createProxy({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Probe Proxy
 */
export const probeProxyMutation = (
  options?: Partial<Options<ProbeProxyData>>,
): UseMutationOptions<ProbeProxyResponse, ProbeProxyError, Options<ProbeProxyData>> => {
  const mutationOptions: UseMutationOptions<
    ProbeProxyResponse,
    ProbeProxyError,
    Options<ProbeProxyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await probeProxy({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Check Proxy
 */
export const checkProxyMutation = (
  options?: Partial<Options<CheckProxyData>>,
): UseMutationOptions<CheckProxyResponse, CheckProxyError, Options<CheckProxyData>> => {
  const mutationOptions: UseMutationOptions<
    CheckProxyResponse,
    CheckProxyError,
    Options<CheckProxyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await checkProxy({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Assign Proxy
 */
export const assignProxyMutation = (
  options?: Partial<Options<AssignProxyData>>,
): UseMutationOptions<AssignProxyResponse, AssignProxyError, Options<AssignProxyData>> => {
  const mutationOptions: UseMutationOptions<
    AssignProxyResponse,
    AssignProxyError,
    Options<AssignProxyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await assignProxy({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Unassign Proxy
 */
export const unassignProxyMutation = (
  options?: Partial<Options<UnassignProxyData>>,
): UseMutationOptions<UnassignProxyResponse, UnassignProxyError, Options<UnassignProxyData>> => {
  const mutationOptions: UseMutationOptions<
    UnassignProxyResponse,
    UnassignProxyError,
    Options<UnassignProxyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await unassignProxy({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Proxy
 */
export const deleteProxyMutation = (
  options?: Partial<Options<DeleteProxyData>>,
): UseMutationOptions<DeleteProxyResponse, DeleteProxyError, Options<DeleteProxyData>> => {
  const mutationOptions: UseMutationOptions<
    DeleteProxyResponse,
    DeleteProxyError,
    Options<DeleteProxyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteProxy({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getWarmingBoardQueryKey = (options?: Options<GetWarmingBoardData>) =>
  createQueryKey('getWarmingBoard', options);

/**
 * Get Warming Board
 */
export const getWarmingBoardOptions = (options?: Options<GetWarmingBoardData>) =>
  queryOptions<
    GetWarmingBoardResponse,
    GetWarmingBoardError,
    GetWarmingBoardResponse,
    ReturnType<typeof getWarmingBoardQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWarmingBoard({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWarmingBoardQueryKey(options),
  });

/**
 * Start Warming
 */
export const startWarmingMutation = (
  options?: Partial<Options<StartWarmingData>>,
): UseMutationOptions<StartWarmingResponse, StartWarmingError, Options<StartWarmingData>> => {
  const mutationOptions: UseMutationOptions<
    StartWarmingResponse,
    StartWarmingError,
    Options<StartWarmingData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await startWarming({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Stop Warming
 */
export const stopWarmingMutation = (
  options?: Partial<Options<StopWarmingData>>,
): UseMutationOptions<StopWarmingResponse, StopWarmingError, Options<StopWarmingData>> => {
  const mutationOptions: UseMutationOptions<
    StopWarmingResponse,
    StopWarmingError,
    Options<StopWarmingData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await stopWarming({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listWarmingChannelsQueryKey = (options?: Options<ListWarmingChannelsData>) =>
  createQueryKey('listWarmingChannels', options);

/**
 * List Warming Channels
 */
export const listWarmingChannelsOptions = (options?: Options<ListWarmingChannelsData>) =>
  queryOptions<
    ListWarmingChannelsResponse,
    ListWarmingChannelsError,
    ListWarmingChannelsResponse,
    ReturnType<typeof listWarmingChannelsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listWarmingChannels({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listWarmingChannelsQueryKey(options),
  });

/**
 * Add Warming Channels
 */
export const addWarmingChannelsMutation = (
  options?: Partial<Options<AddWarmingChannelsData>>,
): UseMutationOptions<
  AddWarmingChannelsResponse,
  AddWarmingChannelsError,
  Options<AddWarmingChannelsData>
> => {
  const mutationOptions: UseMutationOptions<
    AddWarmingChannelsResponse,
    AddWarmingChannelsError,
    Options<AddWarmingChannelsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await addWarmingChannels({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Remove Warming Channel
 */
export const removeWarmingChannelMutation = (
  options?: Partial<Options<RemoveWarmingChannelData>>,
): UseMutationOptions<
  RemoveWarmingChannelResponse,
  RemoveWarmingChannelError,
  Options<RemoveWarmingChannelData>
> => {
  const mutationOptions: UseMutationOptions<
    RemoveWarmingChannelResponse,
    RemoveWarmingChannelError,
    Options<RemoveWarmingChannelData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await removeWarmingChannel({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getWarmingSettingsQueryKey = (options?: Options<GetWarmingSettingsData>) =>
  createQueryKey('getWarmingSettings', options);

/**
 * Get Warming Settings
 */
export const getWarmingSettingsOptions = (options?: Options<GetWarmingSettingsData>) =>
  queryOptions<
    GetWarmingSettingsResponse,
    GetWarmingSettingsError,
    GetWarmingSettingsResponse,
    ReturnType<typeof getWarmingSettingsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWarmingSettings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWarmingSettingsQueryKey(options),
  });

/**
 * Update Warming Settings
 */
export const updateWarmingSettingsMutation = (
  options?: Partial<Options<UpdateWarmingSettingsData>>,
): UseMutationOptions<
  UpdateWarmingSettingsResponse,
  UpdateWarmingSettingsError,
  Options<UpdateWarmingSettingsData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateWarmingSettingsResponse,
    UpdateWarmingSettingsError,
    Options<UpdateWarmingSettingsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateWarmingSettings({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listCampaignsQueryKey = (options?: Options<ListCampaignsData>) =>
  createQueryKey('listCampaigns', options);

/**
 * List Campaigns
 */
export const listCampaignsOptions = (options?: Options<ListCampaignsData>) =>
  queryOptions<
    ListCampaignsResponse,
    ListCampaignsError,
    ListCampaignsResponse,
    ReturnType<typeof listCampaignsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listCampaigns({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listCampaignsQueryKey(options),
  });

/**
 * Create Campaign
 */
export const createCampaignMutation = (
  options?: Partial<Options<CreateCampaignData>>,
): UseMutationOptions<CreateCampaignResponse, CreateCampaignError, Options<CreateCampaignData>> => {
  const mutationOptions: UseMutationOptions<
    CreateCampaignResponse,
    CreateCampaignError,
    Options<CreateCampaignData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createCampaign({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getNeurocommentBoardQueryKey = (options: Options<GetNeurocommentBoardData>) =>
  createQueryKey('getNeurocommentBoard', options);

/**
 * Get Board
 */
export const getNeurocommentBoardOptions = (options: Options<GetNeurocommentBoardData>) =>
  queryOptions<
    GetNeurocommentBoardResponse,
    GetNeurocommentBoardError,
    GetNeurocommentBoardResponse,
    ReturnType<typeof getNeurocommentBoardQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getNeurocommentBoard({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getNeurocommentBoardQueryKey(options),
  });

/**
 * Link Channel
 */
export const linkCampaignChannelMutation = (
  options?: Partial<Options<LinkCampaignChannelData>>,
): UseMutationOptions<
  LinkCampaignChannelResponse,
  LinkCampaignChannelError,
  Options<LinkCampaignChannelData>
> => {
  const mutationOptions: UseMutationOptions<
    LinkCampaignChannelResponse,
    LinkCampaignChannelError,
    Options<LinkCampaignChannelData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await linkCampaignChannel({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Assign Account
 */
export const assignCampaignAccountMutation = (
  options?: Partial<Options<AssignCampaignAccountData>>,
): UseMutationOptions<
  AssignCampaignAccountResponse,
  AssignCampaignAccountError,
  Options<AssignCampaignAccountData>
> => {
  const mutationOptions: UseMutationOptions<
    AssignCampaignAccountResponse,
    AssignCampaignAccountError,
    Options<AssignCampaignAccountData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await assignCampaignAccount({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listCampaignChallengesQueryKey = (options: Options<ListCampaignChallengesData>) =>
  createQueryKey('listCampaignChallenges', options);

/**
 * List Campaign Challenges
 *
 * Recent unsolved bot-challenges across the campaign's channels (captcha queue).
 */
export const listCampaignChallengesOptions = (options: Options<ListCampaignChallengesData>) =>
  queryOptions<
    ListCampaignChallengesResponse,
    ListCampaignChallengesError,
    ListCampaignChallengesResponse,
    ReturnType<typeof listCampaignChallengesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listCampaignChallenges({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listCampaignChallengesQueryKey(options),
  });

export const getNeurocommentRuntimeQueryKey = (options?: Options<GetNeurocommentRuntimeData>) =>
  createQueryKey('getNeurocommentRuntime', options);

/**
 * Get Runtime
 */
export const getNeurocommentRuntimeOptions = (options?: Options<GetNeurocommentRuntimeData>) =>
  queryOptions<
    GetNeurocommentRuntimeResponse,
    GetNeurocommentRuntimeError,
    GetNeurocommentRuntimeResponse,
    ReturnType<typeof getNeurocommentRuntimeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getNeurocommentRuntime({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getNeurocommentRuntimeQueryKey(options),
  });

/**
 * Start
 */
export const startNeurocommentMutation = (
  options?: Partial<Options<StartNeurocommentData>>,
): UseMutationOptions<
  StartNeurocommentResponse,
  StartNeurocommentError,
  Options<StartNeurocommentData>
> => {
  const mutationOptions: UseMutationOptions<
    StartNeurocommentResponse,
    StartNeurocommentError,
    Options<StartNeurocommentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await startNeurocomment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Stop
 */
export const stopNeurocommentMutation = (
  options?: Partial<Options<StopNeurocommentData>>,
): UseMutationOptions<
  StopNeurocommentResponse,
  StopNeurocommentError,
  Options<StopNeurocommentData>
> => {
  const mutationOptions: UseMutationOptions<
    StopNeurocommentResponse,
    StopNeurocommentError,
    Options<StopNeurocommentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await stopNeurocomment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listLogsQueryKey = (options?: Options<ListLogsData>) =>
  createQueryKey('listLogs', options);

/**
 * List Logs
 */
export const listLogsOptions = (options?: Options<ListLogsData>) =>
  queryOptions<
    ListLogsResponse,
    ListLogsError,
    ListLogsResponse,
    ReturnType<typeof listLogsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listLogs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listLogsQueryKey(options),
  });

export const listLogsInfiniteQueryKey = (
  options?: Options<ListLogsData>,
): QueryKey<Options<ListLogsData>> => createQueryKey('listLogs', options, true);

/**
 * List Logs
 */
export const listLogsInfiniteOptions = (options?: Options<ListLogsData>) =>
  infiniteQueryOptions<
    ListLogsResponse,
    ListLogsError,
    InfiniteData<ListLogsResponse>,
    QueryKey<Options<ListLogsData>>,
    string | null | Pick<QueryKey<Options<ListLogsData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListLogsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listLogs({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listLogsInfiniteQueryKey(options),
    },
  );
