// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from '@tanstack/react-query';

import { client } from '../client.gen';
import {
  checkAccount,
  deleteAccount,
  getHealth,
  importAccountTdata,
  listAccounts,
  type Options,
  setAccountPhoto,
  updateAccountProfile,
} from '../sdk.gen';
import type {
  CheckAccountData,
  CheckAccountError,
  CheckAccountResponse,
  DeleteAccountData,
  DeleteAccountError,
  DeleteAccountResponse,
  GetHealthData,
  GetHealthResponse,
  ImportAccountTdataData,
  ImportAccountTdataError,
  ImportAccountTdataResponse,
  ListAccountsData,
  ListAccountsError,
  ListAccountsResponse,
  SetAccountPhotoData,
  SetAccountPhotoError,
  SetAccountPhotoResponse,
  UpdateAccountProfileData,
  UpdateAccountProfileError,
  UpdateAccountProfileResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) =>
  createQueryKey('getHealth', options);

/**
 * Health
 */
export const getHealthOptions = (options?: Options<GetHealthData>) =>
  queryOptions<
    GetHealthResponse,
    DefaultError,
    GetHealthResponse,
    ReturnType<typeof getHealthQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHealth({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHealthQueryKey(options),
  });

export const listAccountsQueryKey = (options?: Options<ListAccountsData>) =>
  createQueryKey('listAccounts', options);

/**
 * List Accounts
 */
export const listAccountsOptions = (options?: Options<ListAccountsData>) =>
  queryOptions<
    ListAccountsResponse,
    ListAccountsError,
    ListAccountsResponse,
    ReturnType<typeof listAccountsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAccounts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listAccountsQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const listAccountsInfiniteQueryKey = (
  options?: Options<ListAccountsData>,
): QueryKey<Options<ListAccountsData>> => createQueryKey('listAccounts', options, true);

/**
 * List Accounts
 */
export const listAccountsInfiniteOptions = (options?: Options<ListAccountsData>) =>
  infiniteQueryOptions<
    ListAccountsResponse,
    ListAccountsError,
    InfiniteData<ListAccountsResponse>,
    QueryKey<Options<ListAccountsData>>,
    | string
    | null
    | Pick<QueryKey<Options<ListAccountsData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListAccountsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listAccounts({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listAccountsInfiniteQueryKey(options),
    },
  );

/**
 * Check Account
 */
export const checkAccountMutation = (
  options?: Partial<Options<CheckAccountData>>,
): UseMutationOptions<CheckAccountResponse, CheckAccountError, Options<CheckAccountData>> => {
  const mutationOptions: UseMutationOptions<
    CheckAccountResponse,
    CheckAccountError,
    Options<CheckAccountData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await checkAccount({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Account Profile
 */
export const updateAccountProfileMutation = (
  options?: Partial<Options<UpdateAccountProfileData>>,
): UseMutationOptions<
  UpdateAccountProfileResponse,
  UpdateAccountProfileError,
  Options<UpdateAccountProfileData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateAccountProfileResponse,
    UpdateAccountProfileError,
    Options<UpdateAccountProfileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateAccountProfile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Account
 */
export const deleteAccountMutation = (
  options?: Partial<Options<DeleteAccountData>>,
): UseMutationOptions<DeleteAccountResponse, DeleteAccountError, Options<DeleteAccountData>> => {
  const mutationOptions: UseMutationOptions<
    DeleteAccountResponse,
    DeleteAccountError,
    Options<DeleteAccountData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteAccount({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Import Account Tdata
 */
export const importAccountTdataMutation = (
  options?: Partial<Options<ImportAccountTdataData>>,
): UseMutationOptions<
  ImportAccountTdataResponse,
  ImportAccountTdataError,
  Options<ImportAccountTdataData>
> => {
  const mutationOptions: UseMutationOptions<
    ImportAccountTdataResponse,
    ImportAccountTdataError,
    Options<ImportAccountTdataData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await importAccountTdata({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Set Account Photo
 */
export const setAccountPhotoMutation = (
  options?: Partial<Options<SetAccountPhotoData>>,
): UseMutationOptions<
  SetAccountPhotoResponse,
  SetAccountPhotoError,
  Options<SetAccountPhotoData>
> => {
  const mutationOptions: UseMutationOptions<
    SetAccountPhotoResponse,
    SetAccountPhotoError,
    Options<SetAccountPhotoData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await setAccountPhoto({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
