"""Data-access repository for the neurocomment domain (issue #114).

Split into submodules to stay within the file-size budget; this package is the
public surface. ``core.db`` re-exports these names so existing
``from core.db import …`` call sites keep working. Importing the package
registers the neurocomment tables in ``core.db._metadata`` (via ``_tables``).

Public functions wrap sync helpers via ``asyncio.to_thread`` and return Pydantic
models / ``None`` / ``bool`` — never raw rows (non-negotiable #2).
"""

from __future__ import annotations

from core.repositories.neurocomment._accounts import (
    ChannelNotInCampaignError,
    assign_account_to_campaign,
    list_campaign_accounts,
    remove_account_from_campaign,
    set_campaign_account_channels,
)
from core.repositories.neurocomment._activity import (
    list_silent_watch_channels,
    stamp_channel_post_seen,
)
from core.repositories.neurocomment._bans import (
    clear_unconfirmed_bans,
    mark_pair_banned,
    stamp_unconfirmed_ban,
    unconfirmed_ban_is_countable,
)
from core.repositories.neurocomment._campaigns import (
    ChannelAlreadyAssignedError,
    create_campaign,
    deactivate_channel,
    delete_campaign,
    fetch_active_campaign_for_channel,
    fetch_active_campaigns_for_channels,
    fetch_campaign,
    link_channel_to_campaign,
    list_active_watch_channels,
    list_campaign_channels,
    list_campaigns,
    set_campaign_status,
    update_campaign_prompt,
    update_solver_enabled,
)
from core.repositories.neurocomment._captcha_giveup import (
    clear_captcha_retry,
    list_captcha_blocked_readiness,
    mark_captcha_gave_up,
    stamp_captcha_retry,
)
from core.repositories.neurocomment._challenges import (
    count_by_outcome,
    evict_cached_decision,
    insert_challenge,
    list_challenged_channels,
    list_failed_for_channel,
    list_failed_for_channels,
    lookup_cached_decision,
    resolve_pending_outcome,
)
from core.repositories.neurocomment._comments import (
    claim_comment,
    fetch_comment,
    fetch_linked_group,
    list_linked_groups,
    list_posted_comments_for_channel_since,
    list_posted_comments_page,
    list_posted_comments_since,
    mark_comment_failed,
    mark_comment_posted,
    reclaim_stale_claims,
    record_comment_msg_id,
    release_claim,
    touch_comment_claim,
    upsert_linked_group,
)
from core.repositories.neurocomment._cooldowns import load_active_cooldowns, persist_cooldown
from core.repositories.neurocomment._deletions import (
    list_delivered_comments_since,
    mark_comments_deleted,
)
from core.repositories.neurocomment._discovery import (
    list_discovery_candidates,
    list_pending_discovery_candidates,
    mark_discovery_qualified,
    replace_discovery_candidates,
)
from core.repositories.neurocomment._inbox import (
    checkpoint_backfill,
    claim_pending_posts,
    complete_post,
    enqueue_post,
    enqueue_post_bounded,
    mark_inbox_stage,
    next_pending_attempt_unix,
    prepare_backfill,
    release_post,
    requeue_processing_posts,
    return_claimed_posts,
)
from core.repositories.neurocomment._joins import (
    count_account_joins_since,
    list_exhausted_watch_channels,
    list_joined_watch_channels,
    mark_watch_channel_join_lost,
    record_join,
)
from core.repositories.neurocomment._pauses import (
    bump_channel_pause,
    clear_channel_pause,
    fetch_channel_paused_until,
    list_expired_channel_pauses,
    release_channel_pause,
)
from core.repositories.neurocomment._quota import (
    count_account_channel_comments_since,
    count_account_comments_since,
    count_channel_comments_per_account_since,
    count_comments_per_account_since,
)
from core.repositories.neurocomment._readiness import (
    clear_join_request,
    clear_rejoin_attempts,
    delete_readiness,
    fetch_readiness,
    list_access_lost_readiness,
    list_campaign_readiness,
    list_channel_readiness,
    list_pending_join_readiness,
    mark_human_skipped,
    mark_rejoin_gave_up,
    stamp_join_request,
    stamp_rejoin_attempt,
    upsert_readiness,
)
from core.repositories.neurocomment._retention import purge_neurocomment_history_older_than
from core.repositories.neurocomment._runtime import (
    get_listener_account_id,
    get_listener_running,
    set_listener_account_id,
    set_listener_running,
)
from core.repositories.neurocomment._settings import (
    load_neurocomment_settings,
    save_neurocomment_settings,
)
from core.repositories.neurocomment._waiting import (
    list_waiting_comments,
    mark_reply_stage,
    park_comment,
    promote_waiting_to_claimed,
    set_comment_dispatch_stage,
)

__all__ = [
    "ChannelAlreadyAssignedError",
    "ChannelNotInCampaignError",
    "assign_account_to_campaign",
    "bump_channel_pause",
    "checkpoint_backfill",
    "claim_comment",
    "claim_pending_posts",
    "clear_captcha_retry",
    "clear_channel_pause",
    "clear_join_request",
    "clear_rejoin_attempts",
    "clear_unconfirmed_bans",
    "complete_post",
    "count_account_channel_comments_since",
    "count_account_comments_since",
    "count_account_joins_since",
    "count_by_outcome",
    "count_channel_comments_per_account_since",
    "count_comments_per_account_since",
    "create_campaign",
    "deactivate_channel",
    "delete_campaign",
    "delete_readiness",
    "enqueue_post",
    "enqueue_post_bounded",
    "evict_cached_decision",
    "fetch_active_campaign_for_channel",
    "fetch_active_campaigns_for_channels",
    "fetch_campaign",
    "fetch_channel_paused_until",
    "fetch_comment",
    "fetch_linked_group",
    "fetch_readiness",
    "get_listener_account_id",
    "get_listener_running",
    "insert_challenge",
    "link_channel_to_campaign",
    "list_access_lost_readiness",
    "list_active_watch_channels",
    "list_campaign_accounts",
    "list_campaign_channels",
    "list_campaign_readiness",
    "list_campaigns",
    "list_captcha_blocked_readiness",
    "list_challenged_channels",
    "list_channel_readiness",
    "list_delivered_comments_since",
    "list_discovery_candidates",
    "list_exhausted_watch_channels",
    "list_expired_channel_pauses",
    "list_failed_for_channel",
    "list_failed_for_channels",
    "list_joined_watch_channels",
    "list_linked_groups",
    "list_pending_discovery_candidates",
    "list_pending_join_readiness",
    "list_posted_comments_for_channel_since",
    "list_posted_comments_page",
    "list_posted_comments_since",
    "list_silent_watch_channels",
    "list_waiting_comments",
    "load_active_cooldowns",
    "load_neurocomment_settings",
    "lookup_cached_decision",
    "mark_captcha_gave_up",
    "mark_comment_failed",
    "mark_comment_posted",
    "mark_comments_deleted",
    "mark_discovery_qualified",
    "mark_human_skipped",
    "mark_inbox_stage",
    "mark_pair_banned",
    "mark_rejoin_gave_up",
    "mark_reply_stage",
    "mark_watch_channel_join_lost",
    "next_pending_attempt_unix",
    "park_comment",
    "persist_cooldown",
    "prepare_backfill",
    "promote_waiting_to_claimed",
    "purge_neurocomment_history_older_than",
    "reclaim_stale_claims",
    "record_comment_msg_id",
    "record_join",
    "release_channel_pause",
    "release_claim",
    "release_post",
    "remove_account_from_campaign",
    "replace_discovery_candidates",
    "requeue_processing_posts",
    "resolve_pending_outcome",
    "return_claimed_posts",
    "save_neurocomment_settings",
    "set_campaign_account_channels",
    "set_campaign_status",
    "set_comment_dispatch_stage",
    "set_listener_account_id",
    "set_listener_running",
    "stamp_captcha_retry",
    "stamp_channel_post_seen",
    "stamp_join_request",
    "stamp_rejoin_attempt",
    "stamp_unconfirmed_ban",
    "touch_comment_claim",
    "unconfirmed_ban_is_countable",
    "update_campaign_prompt",
    "update_solver_enabled",
    "upsert_linked_group",
    "upsert_readiness",
]
