// Neurocomment data access, re-exported from the generated client (FSD: data
// only via shared/api).
export {
  assignCampaignAccountMutation,
  checkCampaignChannelBansMutation,
  clearNeurocommentListenerMutation,
  createCampaignMutation,
  deleteCampaignMutation,
  getNeurocommentBoardOptions as neurocommentBoardQueryOptions,
  getNeurocommentRuntimeOptions as neurocommentRuntimeQueryOptions,
  getNeurocommentSettingsOptions as neurocommentSettingsQueryOptions,
  linkCampaignChannelMutation,
  listCampaignChallengesOptions as campaignChallengesQueryOptions,
  listCampaignsOptions as campaignsQueryOptions,
  listNeurocommentCommentsOptions as neurocommentCommentsQueryOptions,
  removeCampaignAccountMutation,
  removeCampaignChannelMutation,
  retryChallengeMutation,
  setCampaignAccountChannelMutation,
  setCampaignSolverMutation,
  setCampaignStatusMutation,
  startNeurocommentMutation,
  stopNeurocommentMutation,
  updateCampaignPromptMutation,
  updateNeurocommentSettingsMutation,
} from '@/shared/api/@tanstack/react-query.gen';
