// Neurocomment data access, re-exported from the generated client (FSD: data
// only via shared/api).
export {
  adoptCampaignDiscoveryMutation,
  assignCampaignAccountMutation,
  checkCampaignChannelBansMutation,
  clearNeurocommentListenerMutation,
  createCampaignMutation,
  deleteCampaignMutation,
  expandDiscoveryKeywordsMutation,
  getCampaignDiscoveryOptions as campaignDiscoveryQueryOptions,
  getNeurocommentBoardOptions as neurocommentBoardQueryOptions,
  getNeurocommentRuntimeOptions as neurocommentRuntimeQueryOptions,
  getNeurocommentSettingsOptions as neurocommentSettingsQueryOptions,
  linkCampaignChannelMutation,
  listCampaignChallengesOptions as campaignChallengesQueryOptions,
  listCampaignsOptions as campaignsQueryOptions,
  listNeurocommentCommentsOptions as neurocommentCommentsQueryOptions,
  removeCampaignAccountMutation,
  removeCampaignChannelMutation,
  setCampaignAccountChannelMutation,
  setCampaignSolverMutation,
  setCampaignStatusMutation,
  startCampaignDiscoveryMutation,
  startNeurocommentMutation,
  stopNeurocommentMutation,
  updateCampaignPromptMutation,
  updateNeurocommentSettingsMutation,
} from '@/shared/api/@tanstack/react-query.gen';
