// Account write actions, re-exported from the generated TanStack Query mutation
// options (data access only through shared/api, per the FSD ADR).
export {
  addAccountMusicMutation,
  checkAccountMutation,
  createAccountChannelMutation,
  deleteAccountChannelMutation,
  deleteAccountChannelPostMutation,
  deleteAccountMutation,
  editAccountChannelPostMutation,
  importAccountSessionMutation,
  importAccountTdataMutation,
  logoutAccountMutation,
  postAccountStoryMutation,
  publishAccountChannelPostMutation,
  removeAccountMusicMutation,
  removeAccountPhotoMutation,
  removeAccountStoryMutation,
  requestLoginCodeMutation,
  resetAccountSessionMutation,
  setAccountChannelPhotoMutation,
  setAccountPhotoMainMutation,
  setAccountPhotoMutation,
  setAccountStoryPinnedMutation,
  spamCheckAccountMutation,
  startPhoneLoginMutation,
  submitLoginCodeMutation,
  updateAccountChannelMutation,
  updateAccountProfileMutation,
} from '@/shared/api/@tanstack/react-query.gen';
