// Account write actions, re-exported from the generated TanStack Query mutation
// options (data access only through shared/api, per the FSD ADR).
export {
  addAccountMusicMutation,
  cancelAccountTwofaEmailMutation,
  checkAccountMutation,
  clearAccountTwofaEmailMutation,
  confirmAccountTwofaEmailMutation,
  createAccountChannelMutation,
  deleteAccountChannelMutation,
  deleteAccountChannelPostMutation,
  deleteAccountMutation,
  editAccountChannelPostMutation,
  importAccountSessionMutation,
  importAccountTdataMutation,
  logoutAccountMutation,
  postAccountStoryMutation,
  publishAccountChannelPostMutation,
  removeAccountMusicMutation,
  removeAccountPhotoMutation,
  removeAccountStoryMutation,
  removeAccountTwofaMutation,
  requestLoginCodeMutation,
  resendAccountTwofaEmailMutation,
  resetAccountSessionMutation,
  setAccountChannelPhotoMutation,
  setAccountPhotoMainMutation,
  setAccountPhotoMutation,
  setAccountPrivacyMutation,
  setAccountStoryPinnedMutation,
  setAccountTwofaEmailMutation,
  setAccountTwofaMutation,
  setAllAccountsPrivacyMutation,
  spamCheckAccountMutation,
  startPhoneLoginMutation,
  submitLoginCodeMutation,
  updateAccountChannelMutation,
  updateAccountProfileMutation,
} from '@/shared/api/@tanstack/react-query.gen';
